# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
#Import your libraries
import numpy as np
import pandas as pd

# Introduction

In this lab, we will use two datasets. Both datasets contain variables that describe apps from the Google Play Store. We will use our knowledge in feature extraction to process these datasets and prepare them for the use of a ML algorithm.

# Challenge 1 - Loading and Extracting Features from the First Dataset

#### In this challenge, our goals are: 

* Exploring the dataset.
* Identify the columns with missing values.
* Either replacing the missing values in each column or drop the columns.
* Conver each column to the appropriate type.

#### The first dataset contains different information describing the apps. 

Load the dataset into the variable `google_play` in the cell below. The dataset is in the file `googleplaystore.csv`

In [2]:
# Your code here:

google_play = pd.read_csv('../googleplaystore.csv')

#### Examine all variables and their types in the following cell

In [3]:
# Your code here:
google_play.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

#### Since this dataset only contains one numeric column, let's skip the `describe()` function and look at the first 5 rows using the `head()` function

In [4]:
# Your code here:
google_play.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#### We can see that there are a few columns that could be coerced to numeric.

Start with the reviews column. We can evaluate what value is causing this column to be of object type finding the non-numeric values in this column. To do this, we recall the `to_numeric()` function. With this function, we are able to coerce all non-numeric data to null. We can then use the `isnull()` function to subset our dataframe using the True/False column that this function generates.

In the cell below, transform the Reviews column to numeric and assign this new column to the variable `Reviews_numeric`. Make sure to coerce the errors.

In [5]:
# Your code here:
obj_cols = google_play.loc[:, google_play.dtypes == object]
conv_cols = obj_cols.apply(pd.to_numeric, errors = 'coerce')

Next, create a column containing True/False values using the `isnull()` function. Assign this column to the `Reviews_isnull` variable.

In [6]:
# Your code here:
df = pd.DataFrame(conv_cols)
df['Rating'] = google_play['Rating']
df['isnull'] = df['Reviews'].isnull()
df.head()

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Rating,isnull
0,NaN,NaN,159.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,4.1,False
1,NaN,NaN,967.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,3.9,False
2,NaN,NaN,87510.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,4.7,False
3,NaN,NaN,215644.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,4.5,False
4,NaN,NaN,967.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.1,NaN,4.3,False

In [7]:
df['isnull'].value_counts()

False    10840
True         1
Name: isnull, dtype: int64

In [8]:
google_play['Reviews_numeric'] = df['Reviews']

In [9]:
google_play['isnull'] = df['isnull']

In [10]:
google_play.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False

Finally, subset the `google_play` with `Reviews_isnull`. This should give you all the rows that contain non-numeric characters.

Your output should look like:

![Reviews_bool.png](reviews-bool.png)

In [11]:
# Your code here;
Reviews_isnull =  google_play[google_play['isnull']==True]
Reviews_isnull

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

#### We see that Google Play is using a shorthand for millions. 

Let's write a function to transform this data.

Steps:

1. Create a function that returns the correct numeric values of *Reviews*.
1. Define a test string with `M` in the last character.
1. Test your function with the test string. Make sure your function works correctly. If not, modify your functions and test again.

In [12]:
# Your code here

def convert_string_to_numeric(x): 
    if type(x) == float or type(x) == int:
        return x
    if 'k' in x:
        if len(x) > 1:
            return float(x.replace('k', '')) * 1000
        return 1000.0
    if 'M' in x:
        if len(x) > 1:
            return float(x.replace('M', '')) * 1000000
        return 1000000.0
    if 'B' in x:
        return float(x.replace('B', '')) * 1000000000
    return x   
    
    """
    Convert a string value to numeric. If the last character of the string is `M`, obtain the 
    numeric part of the string, multiply it with 1,000,000, then return the result. Otherwise, 
    convert the string to numeric value and return the result.
    
    Args:
        s: The Reviews score in string format.

    Returns:
        The correct numeric value of the Reviews score.
    """
    return x
test_string = '4.0M'

convert_string_to_numeric(test_string) == 4000000

True

In [13]:
convert_string_to_numeric(test_string)

4000000.0

The last step is to apply the function to the `Reviews` column in the following cell:

In [14]:
# Your code here:
google_play['Reviews'] = google_play['Reviews'].apply(convert_string_to_numeric)

Check the non-numeric `Reviews` row again. It should have been fixed now and you should see:

![Reviews_bool_fixed.png](reviews-bool-fixed.png)

In [15]:
# Your code here
Reviews_isnull =  google_play[google_play['isnull']==True]
Reviews_isnull

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3e+06,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

Also check the variable types of `google_play`. The `Reviews` column should be a `float64` type now.

In [16]:
# Your code here:
google_play.dtypes

App                 object
Category            object
Rating             float64
Reviews             object
Size                object
Installs            object
Type                object
Price               object
Content Rating      object
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Reviews_numeric    float64
isnull                bool
dtype: object

#### The next column we will look at is `Size`. We start by looking at all unique values in `Size`:

*Hint: use `unique()` ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html))*.

In [17]:
# Your code here:
google_play.Size.unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

You should have seen lots of unique values of the app sizes.

#### While we can convert most of the `Size` values to numeric in the same way we converted the `Reviews` values, there is one value that is impossible to convert.

What is that badass value? Enter it in the next cell and calculate the proportion of its occurence to the total number of records of `google_play`.

In [18]:
# Your code here:
#badass value = 'Varies with device'
google_play['Size'] = google_play['Size'].apply(convert_string_to_numeric)

In [19]:
google_play['Size'].replace('Varies with device',0)
google_play['Size']= pd.to_numeric(google_play['Size'], errors='coerce')
google_play['Reviews'] = pd.to_numeric(google_play['Reviews'], errors='coerce')
google_play.dtypes

App                 object
Category            object
Rating             float64
Reviews            float64
Size               float64
Installs            object
Type                object
Price               object
Content Rating      object
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Reviews_numeric    float64
isnull                bool
dtype: object

#### While this column may be useful for other types of analysis, we opt to drop it from our dataset. 

There are two reasons. First, the majority of the data are ordinal but a sizeable proportion are missing because we cannot convert them to numerical values. Ordinal data are both numerical and categorical, and they usually can be ranked (e.g. 82k is smaller than 91M). In contrast, non-ordinal categorical data such as blood type and eye color cannot be ranked. The second reason is as a categorical column, it has too many unique values to produce meaningful insights. Therefore, in our case the simplest strategy would be to drop the column.

Drop the column in the cell below (use `inplace=True`)

In [21]:
# Your code here:

#I do not know witch colum it refers to
google_play= google_play.drop(columns='Size')

#### Now let's look at how many missing values are in each column. 

This will give us an idea of whether we should come up with a missing data strategy or give up on the column all together. In the next column, find the number of missing values in each column: 

*Hint: use the `isna()` and `sum()` functions.*

In [22]:
# Your code here:
google_play.isna().sum()

App                   0
Category              0
Rating             1474
Reviews               0
Installs              0
Type                  1
Price                 0
Content Rating        1
Genres                0
Last Updated          0
Current Ver           8
Android Ver           3
Reviews_numeric       1
isnull                0
dtype: int64

You should find the column with the most missing values is now `Rating`.

#### What is the proportion of the missing values in `Rating` to the total number of records?

Enter your answer in the cell below.

In [23]:
# Your code here:
(google_play['Rating'].isna().sum()/google_play['Rating'].count())*100

15.736094800896765

A sizeable proportion of the `Rating` column is missing. A few other columns also contain several missing values.

#### We opt to preserve these columns and remove the rows containing missing data.

In particular, we don't want to drop the `Rating` column because:

* It is one of the most important columns in our dataset. 

* Since the dataset is not a time series, the loss of these rows will not have a negative impact on our ability to analyze the data. It will, however, cause us to lose some meaningful observations. But the loss is limited compared to the gain we receive by preserving these columns.

In the cell below, remove all rows containing at least one missing value. Use the `dropna()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)). Assign the new dataframe to the variable `google_missing_removed`.

In [24]:
# Your code here:
google_play = google_play.dropna()

From now on, we use the `google_missing_removed` variable instead of `google_play`.

#### Next, we look at the `Last Updated` column.

The `Last Updated` column seems to contain a date, though it is classified as an object type. Let's convert this column using the `pd.to_datetime` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)).

In [25]:
# Your code here:
google_play['Last Updated'] = pd.to_datetime(google_play['Last Updated'])

#### The last column we will transform is `Price`. 

We start by looking at the unique values of this column.

In [26]:
# Your code here:
google_play['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

Since all prices are ordinal data without exceptions, we can tranform this column by removing the dollar sign and converting to numeric. We can create a new column called `Price Numerical` and drop the original column.

We will achieve our goal in three steps. Follow the instructions of each step below.

#### First we remove the dollar sign. Do this in the next cell by applying the `str.replace` function to the column to replace `$` with an empty string (`''`).

In [27]:
# Your code here:
google_play['Price'] = google_play['Price'].str.replace('$','')

#### Second step, coerce the `Price Numerical` column to numeric.

In [28]:
# Your code here:
google_play['Price']= pd.to_numeric(google_play['Price'], errors='coerce')

**Finally, drop the original `Price` column.**

In [29]:
# Your code here:
google_play['Price_Numerical'] = google_play['Price']

In [30]:
google_play.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,isnull,Price_Numerical
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,159.0,False,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,967.0,False,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,87510.0,False,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,215644.0,False,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,967.0,False,0.0

In [31]:
google_play = google_play.drop(columns='Price')

Now check the variable types of `google_missing_removed`. Make sure:

* `Size` and `Price` columns have been removed.
* `Rating`, `Reviews`, and `Price Numerical` have the type of `float64`.
* `Last Updated` has the type of `datetime64`.

In [32]:
# Your code here
google_play.dtypes

App                        object
Category                   object
Rating                    float64
Reviews                   float64
Installs                   object
Type                       object
Content Rating             object
Genres                     object
Last Updated       datetime64[ns]
Current Ver                object
Android Ver                object
Reviews_numeric           float64
isnull                       bool
Price_Numerical           float64
dtype: object

# Challenge 2 - Loading and Extracting Features from the Second Dataset

Load the second dataset to the variable `google_reviews`. The data is in the file `googleplaystore_user_reviews.csv`.

In [33]:
# Your code here:

google_review = pd.read_csv('../googleplaystore_user_reviews.csv')

#### This dataset contains the top 100 reviews for each app. 

Let's examine this dataset using the `head` function

In [35]:
# Your code here
google_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#### The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app. 

Columns like `Sentiment_Polarity` and `Sentiment_Subjectivity` are not to our interests because we have no clue how to use them. We do not care about `Translated_Review` because natural language processing is too complex for us at present (in fact the `Sentiment`, `Sentiment_Polarity`, and `Sentiment_Subjectivity` columns are derived from `Translated_Review` the data scientists). 

What we care about in this challenge is `Sentiment`. To be more precise, we care about **what is the proportion of *Positive* sentiment of each app**. This will require us to aggregate the `Sentiment` data by `App` in order to calculate the proportions.

Now that you are clear about what we are trying to achieve, follow the steps below that will walk you through towards our goal.

#### Our first step will be to remove all rows with missing sentiment. 

In the next cell, drop all rows with missing data using the `dropna()` function and assign this new dataframe to `review_missing_removed`.

In [38]:
# Your code here:

review_missing_removed = google_review.dropna()
review_missing_removed.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000

#### Now, use the `value_counts()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) to get a sense on how many apps are in this dataset and their review counts.

In [40]:
# Your code here:
review_missing_removed.App.value_counts()

Bowmasters                                            312
Angry Birds Classic                                   273
Helix Jump                                            273
Calorie Counter - MyFitnessPal                        254
Candy Crush Saga                                      240
Duolingo: Learn Languages Free                        240
Garena Free Fire                                      222
8 Ball Pool                                           219
Calorie Counter - Macros                              200
10 Best Foods for You                                 194
CBS Sports App - Scores, News, Stats & Watch Live     192
Google Photos                                         191
Alto's Adventure                                      175
8fit Workouts & Meal Planner                          171
DRAGON BALL LEGENDS                                   167
Candy Crush Soda Saga                                 166
Clash Royale                                          165
Adobe Acrobat Reader                                  162
Episode - Choose Your Story                           160
Flow Free                                             154
Block Puzzle                                          154
Bubble Shooter                                        145
Calorie Counter - MyNetDiary                          139
Agar.io                                               136
Calorie Counter & Diet Tracker                        135
Cooking Fever                                         135
Galaxy Attack: Alien Shooter                          134
Colorfy: Coloring Book for Adults - Free              133
Gardenscapes                                          133
Facebook                                              132
                                                     ...
Google Primer                                           2
Amazon Prime Video                                      2
Google+                                                 2
Extreme Car Driving Simulator                           2
Draw Your Game                                          2
CBS News                                                1
Draw A Stickman                                         1
Fruit Block - Puzzle Legend                             1
Bed Time Fan - White Noise Sleep Sounds                 1
HD Camera                                               1
Free Live Talk-Video Call                               1
Caf - Mon Compte                                        1
DashClock Widget                                        1
HomeWork                                                1
Caller ID +                                             1
Best Fiends - Free Puzzle Game                          1
All-in-One Mahjong 3 FREE                               1
Google Trips - Travel Planner                           1
Draw a Stickman: EPIC 2                                 1
Draw In                                                 1
GPS Map Free                                            1
Apartment Decorating Ideas                              1
Best Ovulation Tracker Fertility Calendar App Glow      1
Google Slides                                           1
Calculator - unit converter                             1
Drawing for Kids Learning Games for Toddlers age 3      1
Daily Workouts - Exercise Fitness Routine Trainer       1
Discover Mobile                                         1
CallApp: Caller ID, Blocker & Phone Call Recorder       1
Calendar+ Schedule Planner App                          1
Name: App, Length: 865, dtype: int64

#### Now the tough part comes. Let's plan how we will achieve our goal:

1. We will count the number of reviews that contain *Positive* in the `Sentiment` column.

1. We will create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app.

1. We will then loop the new dataframe to calculate the postivie review portion of each app.

#### Step 1: Count the number of positive reviews.

In the following cell, write a function that takes a column and returns the number of times *Positive* appears in the column. 

*Hint: One option is to use the `np.where()` function ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html)).*

In [50]:
# Your code below


def positive_function(x):

    if np.where(x = 'Positive'):
        return 1
    else:
        return 0

    """
    Count how many times the string `Positive` appears in a column (exact string match).
    
    Args:
        x: data column
    
    Returns:
        The number of occurrences of `Positive` in the column data.
    """

In [60]:
review_missing_removed['Positive'] = np.where(review_missing_removed['Sentiment'] == 'Positive', 1, 0)
review_missing_removed['Total'] = 1
review_missing_removed.head()

/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Positive,Total
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333,1,1
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462,1,1
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000,1,1
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000,1,1
5,10 Best Foods for You,Best way,Positive,1.00,0.300000,1,1

#### Step 2: Create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app

We will group `review_missing_removed` by the `App` column, then aggregate the grouped dataframe on the number of positive reviews and the total review counts of each app. The result will be assigned to a new variable `google_agg`. Here is the ([documentation on how to achieve it](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). Take a moment or two to read the documentation and google examples because it is pretty complex.

When you obtain `google_agg`, check its values to make sure it has an `App` column as its index as well as a `Positive` column and a `Total` column. Your output should look like:

![Positive Reviews Agg](positive-review-agg.png)

*Hint: Use `positive_function` you created earlier as part of the param passed to the `agg()` function in order to aggregate the number of positive reviews.*

#### Bonus:

As of Pandas v0.23.4, you may opt to supply an array or an object to `agg()`. If you use the array param, you'll need to rename the columns so that their names are `Positive` and `Total`. Using the object param will allow you to create the aggregated columns with the desirable names without renaming them. However, you will probably encounter a warning indicating supplying an object to `agg()` will become outdated. It's up to you which way you will use. Try both ways out. Any way is fine as long as it works.

In [65]:
# Your code here:
google_agg = review_missing_removed.pivot_table(index='App', values= ['Positive','Total'], aggfunc='sum')

Print the first 5 rows of `google_agg` to check it.

In [66]:
# Your code here
google_agg.head()

                                  Positive  Total
App
10 Best Foods for You                  162    194
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40
11st                                    23     39
1800 Contacts - Lens Store              64     80
1LINE – One Line with One Touch         27     38

#### Add a derived column to `google_agg` that is the ratio of the `Positive` and the `Total` columns. Call this column `Positive Ratio`. 

Make sure to account for the case where the denominator is zero using the `np.where()` function.

In [69]:
# Your code here:
google_agg['Ratio'] = google_agg['Positive']/google_agg['Total']
google_agg.head()

                                  Positive  Total     Ratio
App
10 Best Foods for You                  162    194  0.835052
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40  0.775000
11st                                    23     39  0.589744
1800 Contacts - Lens Store              64     80  0.800000
1LINE – One Line with One Touch         27     38  0.710526

#### Now drop the `Positive` and `Total` columns. Do this with `inplace=True`.

In [74]:
# Your code here:
google_agg.drop(columns=['Positive', 'Total'], inplace= True)

Print the first 5 rows of `google_agg`. Your output should look like:

![Positive Reviews Agg](positive-review-ratio.png)

In [75]:
# Your code here:
google_agg.head()

                                     Ratio
App
10 Best Foods for You             0.835052
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室  0.775000
11st                              0.589744
1800 Contacts - Lens Store        0.800000
1LINE – One Line with One Touch   0.710526

# Challenge 3 - Join the Dataframes

In this part of the lab, we will join the two dataframes and obtain a dataframe that contains features we can use in our ML algorithm.

In the next cell, join the `google_missing_removed` dataframe with the `google_agg` dataframe on the `App` column. Assign this dataframe to the variable `google`.

In [84]:
# Your code here:
df_merge_col = pd.merge(google_play, google_agg, on='App')

#### Let's look at the final result using the `head()` function. Your final product should look like:

![Final Product](google-final-head.png)

In [85]:
# Your code here:
df_merge_col

,App,Category,Rating,Reviews,Installs,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,isnull,Price_Numerical,Ratio
0,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,967.0,False,0.0,0.590909
1,Coloring book moana,FAMILY,3.9,974.0,"500,000+",Free,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,974.0,False,0.0,0.590909
2,Garden Coloring Book,ART_AND_DESIGN,4.4,13791.0,"1,000,000+",Free,Everyone,Art & Design,2017-09-20,2.9.2,3.0 and up,13791.0,False,0.0,0.711111
3,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216.0,"5,000,000+",Free,Everyone,Art & Design,2018-08-03,2.2.5,4.0.3 and up,194216.0,False,0.0,1.000000
4,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654.0,"100,000+",Free,Everyone,Art & Design,2018-03-20,1.1,4.0.3 and up,654.0,False,0.0,0.605263
5,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260.0,"500,000+",Free,Everyone,Art & Design;Creativity,2017-10-11,1.0.8,4.0.3 and up,20260.0,False,0.0,0.763158
6,Animated Photo Editor,ART_AND_DESIGN,4.1,203.0,"100,000+",Free,Everyone,Art & Design,2018-03-21,1.03,4.0.3 and up,203.0,False,0.0,0.600000
7,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035.0,"100,000+",Free,Everyone,Art & Design,2018-07-19,2.20,4.0 and up,5035.0,False,0.0,0.791667
8,Easy Origami Ideas,ART_AND_DESIGN,4.2,1015.0,"100,000+",Free,Everyone,Art & Design,2018-01-06,1.1.0,4.1 and up,1015.0,False,0.0,0.500000
9,Floor Plan Creator,ART_AND_DESIGN,4.1,36639.0,"5,000,000+",Free,Everyone,Art & Design,2018-07-14,Varies with device,2.3.3 and up,36639.0,False,0.0,0.702703
10,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531.0,"10,000,000+",Free,Everyone,Art & Design,2018-07-31,1.6.1,4.1 and up,174531.0,False,0.0,0.789474
11,CDL Practice Test 2018 Edition,AUTO_AND_VEHICLES,4.9,7774.0,"100,000+",Free,Everyone,Auto & Vehicles,2018-07-03,1.7,4.2 and up,7774.0,False,0.0,0.875000
12,Free VIN Report for Used Cars,AUTO_AND_VEHICLES,4.6,2431.0,"100,000+",Free,Everyone,Auto & Vehicles,2018-06-12,1.37,4.0 and up,2431.0,False,0.0,0.742857
13,DMV Permit Practice Test 2018 Edition,AUTO_AND_VEHICLES,4.9,6090.0,"100,000+",Free,Everyone,Auto & Vehicles,2018-07-03,1.7,4.2 and up,6090.0,False,0.0,0.882353
14,"Android Auto - Maps, Media, Messaging & Voice",AUTO_AND_VEHICLES,4.2,271920.0,"10,000,000+",Free,Teen,Auto & Vehicles,2018-07-11,Varies with device,5.0 and up,271920.0,False,0.0,0.967742
15,Best Car Wallpapers,AUTO_AND_VEHICLES,4.5,994.0,"100,000+",Free,Everyone,Auto & Vehicles,2018-03-27,1.6,4.1 and up,994.0,False,0.0,0.333333
16,BEST CAR SOUNDS,AUTO_AND_VEHICLES,4.3,348.0,"100,000+",Free,Everyone,Auto & Vehicles,2018-07-29,1.0.3,2.3 and up,348.0,False,0.0,0.675676
17,AutoScout24 Switzerland – Find your new car,AUTO_AND_VEHICLES,4.6,13372.0,"1,000,000+",Free,Everyone,Auto & Vehicles,2018-08-03,Varies with device,Varies with device,13372.0,False,0.0,0.810811
18,Fuelio: Gas log & costs,AUTO_AND_VEHICLES,4.6,65786.0,"1,000,000+",Free,Everyone,Auto & Vehicles,2018-08-02,Varies with device,4.0.3 and up,65786.0,False,0.0,0.829545
19,"BestCam Selfie-selfie, beauty camera, photo ed...",BEAUTY,3.9,1739.0,"500,000+",Free,Everyone,Beauty,2018-07-12,1.0.6,4.0.3 and up,1739.0,False,0.0,0.282828
20,Hairstyles step by step,BEAUTY,4.6,4369.0,"100,000+",Free,Everyone,Beauty,2018-07-25,1.9,4.0.3 and up,4369.0,False,0.0,0.827160
21,Filters for Selfie,BEAUTY,4.3,8572.0,"1,000,000+",Free,Everyone,Beauty,2018-05-10,1.1.0,4.0 and up,8572.0,False,0.0,0.492063
22,Beauty Camera - Selfie Camera,BEAUTY,4.0,113715.0,"10,000,000+",Free,Everyone,Beauty,2017-08-03,Varies with device,Varies with device,113715.0,False,0.0,0.638889
23,Filters for B Live,BEAUTY,4.4,2280.0,"500,000+",Free,Everyone,Beauty,2018-05-14,1.1.0,4.0 and up,2280.0,False,0.0,0.433333
24,Dresses Ideas & Fashions +3000,BEAUTY,4.5,473.0,"100,000+",Free,Mature 17+,Beauty,2017-03-01,1.0.2.0,1.6 and up,473.0,False,0.0,0.793103
25,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814080.0,"100,000,000+",Free,Teen,Books & Reference,2018-07-27,Varies with device,Varies with device,814080.0,False,0.0,0.555556
26,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814151.0,"100,000,000+",Free,Teen,Books & Reference,2018-07-27,Varies with device,Varies with device,814151.0,False,0.0,0.555556
27,Cool Reader,BOOKS_AND_REFERENCE,4.5,246315.0,"10,000,000+",Free,Everyone,Books & Reference,2015-07-17,Varies with device,1.5 and up,246315.0,False,0.0,0.631579
28,Dictionary - Merriam-Webster,BOOKS_AND_REFERENCE,4.5,454060.0,"10,000,000+",Free,Everyone,Books & Reference,2018-05-18,Varies with device,Varies with device,454060.0,False,0.0,0.750000
29,Dictionary - Merriam-Webster,BOOKS_AND_REFERENCE,4.5,454412.0,"10,000,000+",Free,Everyone,Books & Reference,2018-05-18,Varies with device,Varies with device,454412.0,False,0.0,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,Akinator,FAMILY,4.3,1805398.0,"50,000,000+",Free,Teen,Entertainment,2018-06-11,6.5.2,4.4 and up,1805398.0,False,0.0,0.500000
1199,Dog Sim Online: Raise a Family,FAMILY,4.6,94989.0,"5,000,000+",Free,Teen,Simulation,2018-04-22,8.6,4.0 and up,94989.0,False,0.0,0.500000
1200,Color by Number - Draw Sandbox Pixel Art,FAMILY,4.6,10247.0,"1,000,000+",Free,Everyone,Entertainment,2018-07-27,1.3.13,4.1 and up,10247.0,False,0.0,0.597826
1201,A+ Mobile,FINANCE,3.9,730.0,"10,000+",Free,Everyone,Finance,2018-06-26,5.4.4,4.4 and up,730.0,False,0.0,0.678571
1202,Build a Bridge!,FAMILY,4.6,263454.0,"10,000,000+",Free,Everyone,Puzzle,2018-08-02,2.1.1,4.1 and up,263454.0,False,0.0,0.581395
1203,Find a Way: Addictive Puzzle,FAMILY,4.8,39480.0,"500,000+",Free,Everyone,Puzzle,2017-06-16,4.1.1,4.1 and up,39480.0,False,0.0,0.633333
1204,Comptia A+ 220-901 & 220-902,FAMILY,4.4,174.0,"10,000+",Free,Everyone,Education,2018-04-19,2.0.7,4.1 and up,174.0,False,0.0,0.896552
1205,Azar,COMMUNICATION,4.2,1092337.0,"50,000,000+",Free,Mature 17+,Communication,2018-07-24,Varies with device,Varies with device,1092337.0,False,0.0,0.413043
1206,4 in a Row,GAME,3.8,4257.0,"500,000+",Free,Everyone,Board,2018-05-13,Varies with device,Varies with device,4257.0,False,0.0,0.850000
1207,Asphalt 8: Airborne,GAME,4.5,8389714.0,"100,000,000+",Free,Teen,Racing,2018-07-04,3.7.1a,4.0.3 and up,8389714.0,False,0.0,0.534247
1208,Basketball Stars,SPORTS,4.4,867920.0,"10,000,000+",Free,Everyone,Sports,2018-07-14,1.16.2,4.0.3 and up,867920.0,False,0.0,0.494382
1209,Fake Call - Fake Caller ID,PRODUCTIVITY,4.3,154668.0,"10,000,000+",Free,Everyone,Productivity,2018-08-02,Varies with device,Varies with device,154668.0,False,0.0,0.671642
1210,Four In A Line Free,GAME,4.3,133195.0,"5,000,000+",Free,Everyone,Board,2018-06-11,1.58,4.1 and up,133195.0,False,0.0,0.666667
1211,AutoCAD - DWG Viewer & Editor,PRODUCTIVITY,4.2,145088.0,"10,000,000+",Free,Everyone,Productivity,2018-07-23,4.5.19,4.4 and up,145088.0,False,0.0,0.444444
1212,Fortune City - A Finance App,FINANCE,4.6,49275.0,"500,000+",Free,Everyone,Finance,2018-07-17,2.0.3.1,4.4 and up,49275.0,False,0.0,0.854167
1213,Draw A Stickman,GAME,3.4,29265.0,"1,000,000+",Free,Everyone,Adventure,2017-05-19,1.1.0,4.0.3 and up,29265.0,False,0.0,0.000000
1214,Be A Legend: Soccer,SPORTS,3.8,85763.0,"1,000,000+",Free,Everyone,Sports,2015-08-24,2.8.0.17,3.0 and up,85763.0,False,0.0,0.336735
1215,Bible,BOOKS_AND_REFERENCE,4.7,2440695.0,"100,000,000+",Free,Teen,Books & Reference,2018-08-02,Varies with device,Varies with device,2440695.0,False,0.0,0.835052
1216,Cat Sim Online: Play with Cats,FAMILY,4.6,137198.0,"5,000,000+",Free,Everyone 10+,Simulation,2018-04-22,3.7,4.0 and up,137198.0,False,0.0,0.737705
1217,Four In A Line,GAME,3.8,22191.0,"1,000,000+",Free,Everyone,Board,2015-05-04,1.10,2.3 and up,22191.0,False,0.0,0.803279
1218,Hay Day,FAMILY,4.5,10053186.0,"100,000,000+",Free,Everyone,Casual,2018-06-28,1_39_93,4.0.3 and up,10053186.0,False,0.0,0.557377
1219,Fruit Ninja®,GAME,4.3,5091448.0,"100,000,000+",Free,Everyone,Arcade,2018-07-12,2.6.7.487220,4.1 and up,5091448.0,False,0.0,0.709677
1220,"DU Recorder – Screen Recorder, Video Editor, Live",VIDEO_PLAYERS,4.8,2588730.0,"50,000,000+",Free,Everyone,Video Players & Editors,2018-07-30,1.7.1.3,5.0 and up,2588730.0,False,0.0,0.724138
1221,Bad Piggies,FAMILY,4.3,1168959.0,"50,000,000+",Free,Everyone,Puzzle,2017-05-03,2.3.3,4.1 and up,1168959.0,False,0.0,0.480519
1222,Dumb Ways to Die 2: The Games,FAMILY,4.2,1671658.0,"50,000,000+",Free,Teen,Casual,2018-07-12,Varies with device,Varies with device,1671658.0,False,0.0,0.540541
1223,"AD - Nieuws, Sport, Regio & Entertainment",NEWS_AND_MAGAZINES,3.7,10369.0,"1,000,000+",Free,Everyone,News & Magazines,2018-07-28,Varies with device,Varies with device,10369.0,False,0.0,0.684211
1224,AppLock,TOOLS,4.4,4931562.0,"100,000,000+",Free,Everyone,Tools,2018-06-11,Varies with device,Varies with device,4931562.0,False,0.0,0.461538
1225,Diary with lock password,LIFESTYLE,4.3,179139.0,"5,000,000+",Free,Everyone,Lifestyle,2017-11-01,3.5.3,4.0.3 and up,179139.0,False,0.0,0.730769
1226,Avakin Life - 3D virtual world,FAMILY,4.4,1275373.0,"10,000,000+",Free,Teen,Role Playing,2018-07-03,1.021.10,4.1 and up,1275373.0,False,0.0,0.753623
1227,A+ Gallery - Photos & Videos,PHOTOGRAPHY,4.5,223941.0,"10,000,000+",Free,Everyone,Photography,2018-08-06,Varies with device,Varies with device,223941.0,False,0.0,0.585366