# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [1]:
# import required libraries
import numpy as np
import pandas as pd

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [2]:
# enter your code here
orders = pd.read_csv("../../lab-subsetting-and-descriptive-stats/your-code/Orders.zip")
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [3]:
#¿Cuantas prendas compradas hay en el df?
orders.shape

(397924, 14)

In [4]:
#¿Cuántos CustomerID hay?
grouped_customers = orders.groupby('CustomerID')
len(grouped_customers)

4339

In [10]:
# Me cercioro de que no hay CustomerID repetidos
customer_unique = orders['CustomerID'].unique()
len(customer_unique)

4339

In [6]:
# ¿Cuantos 'amount_spent' hay por cada CustomerID?

grouped_customers = orders.groupby('CustomerID')
amount_spent = grouped_customers['amount_spent'].value_counts()
amount_spent

CustomerID  amount_spent
12346       77183.60         1
12347       15.00           24
            17.00           16
            13.20           14
            19.80           12
            30.00           10
            23.40            7
            10.20            6
            12.50            5
            17.70            5
            20.40            5
            8.40             4
            8.50             4
            24.96            4
            34.00            4
            17.40            3
            22.50            3
            35.40            3
            38.25            3
            7.80             2
            11.70            2
            12.60            2
            13.00            2
            13.16            2
            18.00            2
            19.90            2
            25.50            2
            35.70            2
            39.60            2
            45.00            2
                            ..
18287       9.36             3
            10.08            3
            10.20            3
            18.72            3
            25.20            3
            69.60            3
            5.04             2
            6.96             2
            14.04            2
            20.40            2
            37.50            2
            50.40            2
            81.12            2
            12.60            1
            13.68            1
            15.12            1
            16.60            1
            17.00            1
            17.40            1
            17.70            1
            25.00            1
            25.44            1
            30.60            1
            34.00            1
            39.84            1
            45.00            1
            52.20            1
            53.10            1
            59.40            1
            87.00            1
Name: amount_spent, Length: 139901, dtype: int64

In [9]:
# Esta es la suma total que se ha gastado cada Customer

amount_per_customer = orders.groupby("CustomerID")["amount_spent"].sum()
amount_per_customer

CustomerID
12346    77183.60
12347     4310.00
12348     1797.24
12349     1757.55
12350      334.40
12352     2506.04
12353       89.00
12354     1079.40
12355      459.40
12356     2811.43
12357     6207.67
12358     1168.06
12359     6372.58
12360     2662.06
12361      189.90
12362     5226.23
12363      552.00
12364     1313.10
12365      641.38
12367      168.90
12370     3545.69
12371     1887.96
12372     1298.04
12373      364.60
12374      742.93
12375      457.50
12377     1628.12
12378     4008.62
12379      852.24
12380     2724.81
           ...
18242     2232.49
18245     2567.06
18246      596.10
18248      804.02
18249       95.34
18250      349.27
18251     4314.72
18252      526.67
18255      103.30
18257     2337.63
18259     2338.60
18260     2643.20
18261      324.24
18262      149.48
18263     1213.16
18265      801.51
18268       25.50
18269      168.60
18270      283.15
18272     3078.58
18273      204.00
18274      175.92
18276      335.86
18277      110.38
18278      173.90
18280      180.60
18281       80.82
18282      178.05
18283     2094.88
18287     1837.28
Name: amount_spent, Length: 4339, dtype: float64

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

In [13]:
vip_customers = amount_per_customer.sort_values(ascending=False)
vip_customers.head()

CustomerID
14646    280206.02
18102    259657.30
17450    194550.79
16446    168472.50
14911    143825.06
Name: amount_spent, dtype: float64

In [17]:
# This is the top 1
vip_1_info = orders[orders['CustomerID'] == 14646]
vip_1_info

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_per_customer
24451,37952,539491,21981,2010,12,1,10,pack of 12 woodland tissues,12,2010-12-20 10:09:00,0.29,14646,Netherlands,3.48,NaN
24452,37953,539491,21986,2010,12,1,10,pack of 12 pink polkadot tissues,12,2010-12-20 10:09:00,0.29,14646,Netherlands,3.48,NaN
24453,37954,539491,22720,2010,12,1,10,set of 3 cake tins pantry design,2,2010-12-20 10:09:00,4.95,14646,Netherlands,9.90,NaN
24454,37955,539491,21931,2010,12,1,10,jumbo storage bag suki,1,2010-12-20 10:09:00,1.95,14646,Netherlands,1.95,NaN
24455,37956,539491,22613,2010,12,1,10,pack of 20 spaceboy napkins,2,2010-12-20 10:09:00,0.85,14646,Netherlands,1.70,NaN
24456,37957,539491,20751,2010,12,1,10,funky washing up gloves assorted,1,2010-12-20 10:09:00,2.10,14646,Netherlands,2.10,NaN
24457,37958,539491,21246,2010,12,1,10,red retrospot big bowl,2,2010-12-20 10:09:00,4.95,14646,Netherlands,9.90,NaN
24458,37959,539491,22960,2010,12,1,10,jam making set with jars,1,2010-12-20 10:09:00,4.25,14646,Netherlands,4.25,NaN
24459,37960,539491,22355,2010,12,1,10,charlotte bag suki design,2,2010-12-20 10:09:00,0.85,14646,Netherlands,1.70,NaN
24460,37961,539491,21123,2010,12,1,10,set/10 ivory polkadot party candles,2,2010-12-20 10:09:00,1.25,14646,Netherlands,2.50,NaN
24461,37962,539491,47599A,2010,12,1,10,pink party bags,2,2010-12-20 10:09:00,2.10,14646,Netherlands,4.20,NaN
24462,37963,539491,22331,2010,12,1,10,woodland party bag + sticker set,2,2010-12-20 10:09:00,1.65,14646,Netherlands,3.30,NaN
24463,37964,539491,22333,2010,12,1,10,retrospot party bag + sticker set,2,2010-12-20 10:09:00,1.65,14646,Netherlands,3.30,NaN
24464,37965,539491,22315,2010,12,1,10,200 red + white bendy straws,1,2010-12-20 10:09:00,1.25,14646,Netherlands,1.25,NaN
24465,37966,539491,22445,2010,12,1,10,pencil case life is beautiful,1,2010-12-20 10:09:00,2.95,14646,Netherlands,2.95,NaN
24466,37967,539491,POST,2010,12,1,10,postage,1,2010-12-20 10:09:00,15.00,14646,Netherlands,15.00,NaN
25478,40190,539731,21212,2010,12,2,15,pack of 72 retrospot cake cases,240,2010-12-21 15:05:00,0.42,14646,Netherlands,100.80,NaN
25479,40191,539731,22858,2010,12,2,15,easter tin keepsake,108,2010-12-21 15:05:00,1.45,14646,Netherlands,156.60,NaN
25480,40192,539731,84459A,2010,12,2,15,pink metal chicken heart,192,2010-12-21 15:05:00,1.25,14646,Netherlands,240.00,NaN
25481,40193,539731,84459B,2010,12,2,15,yellow metal chicken heart,192,2010-12-21 15:05:00,1.25,14646,Netherlands,240.00,NaN
25482,40194,539731,22859,2010,12,2,15,easter tin bunny bouquet,108,2010-12-21 15:05:00,1.45,14646,Netherlands,156.60,NaN
25483,40195,539731,22856,2010,12,2,15,assorted easter decorations bells,288,2010-12-21 15:05:00,1.06,14646,Netherlands,305.28,NaN
25484,40196,539731,21935,2010,12,2,15,suki shoulder bag,100,2010-12-21 15:05:00,1.45,14646,Netherlands,145.00,NaN
25485,40197,539731,22383,2010,12,2,15,lunch bag suki design,100,2010-12-21 15:05:00,1.45,14646,Netherlands,145.00,NaN
25486,40198,539731,21213,2010,12,2,15,pack of 72 skull cake cases,120,2010-12-21 15:05:00,0.42,14646,Netherlands,50.40,NaN
25487,40199,539731,21558,2010,12,2,15,skull lunch box with cutlery,120,2010-12-21 15:05:00,2.10,14646,Netherlands,252.00,NaN
25488,40200,539731,21930,2010,12,2,15,jumbo storage bag skulls,100,2010-12-21 15:05:00,1.65,14646,Netherlands,165.00,NaN
25489,40201,539731,22417,2010,12,2,15,pack of 60 spaceboy cake cases,120,2010-12-21 15:05:00,0.42,14646,Netherlands,50.40,NaN
25490,40202,539731,22474,2010,12,2,15,spaceboy tv dinner tray,16,2010-12-21 15:05:00,4.25,14646,Netherlands,68.00,NaN
25491,40203,539731,22472,2010,12,2,15,tv dinner tray dolly girl,16,2010-12-21 15:05:00,4.25,14646,Netherlands,68.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394398,534933,581175,23597,2011,12,3,15,paper bunting paisley park,80,2011-12-07 15:16:00,2.55,14646,Netherlands,204.00,NaN
394399,534934,581175,23483,2011,12,3,15,hanging butterfly t-light holder,72,2011-12-07 15:16:00,1.04,14646,Netherlands,74.88,NaN
394400,534935,581175,23447,2011,12,3,15,pink bunny easter egg basket,144,2011-12-07 15:16:00,1.45,14646,Netherlands,208.80,NaN
394401,534936,581175,47593B,2011,12,3,15,scottie dogs baby bib,96,2011-12-07 15:16:00,0.39,14646,Netherlands,37.44,NaN
394402,534937,581175,23081,2011,12,3,15,green metal box army supplies,16,2011-12-07 15:16:00,7.50,14646,Netherlands,120.00,NaN
394403,534938,581175,23080,2011,12,3,15,red metal box top secret,16,2011-12-07 15:16:00,7.50,14646,Netherlands,120.00,NaN
394404,534939,581175,21671,2011,12,3,15,red spot ceramic drawer knob,96,2011-12-07 15:16:00,1.25,14646,Netherlands,120.00,NaN
394405,534940,581175,21731,2011,12,3,15,red toadstool led night light,24,2011-12-07 15:16:00,1.65,14646,Netherlands,39.60,NaN
394406,534941,581175,22467,2011,12,3,15,gumball coat rack,72,2011-12-07 15:16:00,2.10,14646,Netherlands,151.20,NaN
394407,534942,581175,22487,2011,12,3,15,white wood garden plant ladder,4,2011-12-07 15:16:00,8.50,14646,Netherlands,34.00,NaN
394408,534943,581175,22489,2011,12,3,15,pack of 12 traditional crayons,144,2011-12-07 15:16:00,0.36,14646,Netherlands,51.84,NaN
394409,534944,581175,22563,2011,12,3,15,happy stencil craft,72,2011-12-07 15:16:00,1.06,14646,Netherlands,76.32,NaN
394410,534945,581175,22846,2011,12,3,15,bread bin diner style red,4,2011-12-07 15:16:00,14.95,14646,Netherlands,59.80,NaN
394411,534946,581175,23154,2011,12,3,15,set of 4 jam jar magnets,120,2011-12-07 15:16:00,1.85,14646,Netherlands,222.00,NaN
394412,534947,581175,23171,2011,12,3,15,regency tea plate green,48,2011-12-07 15:16:00,1.45,14646,Netherlands,69.60,NaN
394413,534948,581175,23172,2011,12,3,15,regency tea plate pink,48,2011-12-07 15:16:00,1.45,14646,Netherlands,69.60,NaN
394414,534949,581175,23209,2011,12,3,15,lunch bag vintage doily,100,2011-12-07 15:16:00,1.45,14646,Netherlands,145.00,NaN
394415,534950,581175,23290,2011,12,3,15,spaceboy childrens bowl,144,2011-12-07 15:16:00,1.05,14646,Netherlands,151.20,NaN
394416,534951,581175,22867,2011,12,3,15,hand warmer bird design,96,2011-12-07 15:16:00,1.85,14646,Netherlands,177.60,NaN
394417,534952,581175,23084,2011,12,3,15,rabbit night light,1440,2011-12-07 15:16:00,1.79,14646,Netherlands,2577.60,NaN
394418,534953,581175,22343,2011,12,3,15,party pizza dish red retrospot,96,2011-12-07 15:16:00,0.19,14646,Netherlands,18.24,NaN
394419,534954,581176,22561,2011,12,3,15,wooden school colouring set,72,2011-12-07 15:19:00,1.45,14646,Netherlands,104.40,NaN
394420,534955,581176,22795,2011,12,3,15,sweetheart recipe book stand,16,2011-12-07 15:19:00,5.95,14646,Netherlands,95.20,NaN
394421,534956,581176,23112,2011,12,3,15,parisienne curio cabinet,12,2011-12-07 15:19:00,6.65,14646,Netherlands,79.80,NaN
394422,534957,581176,23118,2011,12,3,15,parisienne jewellery drawer,16,2011-12-07 15:19:00,6.65,14646,Netherlands,106.40,NaN
394423,534958,581176,22908,2011,12,3,15,pack of 20 napkins red apples,96,2011-12-07 15:19:00,0.72,14646,Netherlands,69.12,NaN
394424,534959,581176,22907,2011,12,3,15,pack of 20 napkins pantry design,96,2011-12-07 15:19:00,0.72,14646,Netherlands,69.12,NaN
394425,534960,581176,22029,2011,12,3,15,spaceboy birthday card,72,2011-12-07 15:19:00,0.36,14646,Netherlands,25.92,NaN
394426,534961,581176,22712,2011,12,3,15,card dolly girl,72,2011-12-07 15:19:00,0.36,14646,Netherlands,25.92,NaN
395497,537783,581338,23344,2011,12,4,12,jumbo bag 50's christmas,140,2011-12-08 12:12:00,1.79,14646,Netherlands,250.60,NaN

In [21]:
#vip_customers_country = vip_customers['Country']

vip_2_info = orders[orders['CustomerID'] == 18102]
vip_2_info

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_per_customer
10784,16425,537657,82484,2010,12,2,16,wood black board ant white finish,408,2010-12-07 16:42:00,4.78,18102,United Kingdom,1950.24,NaN
10785,16426,537657,22830,2010,12,2,16,utilty cabinet with hooks,30,2010-12-07 16:42:00,19.84,18102,United Kingdom,595.20,NaN
10786,16427,537657,22189,2010,12,2,16,cream heart card holder,972,2010-12-07 16:42:00,2.31,18102,United Kingdom,2245.32,NaN
10787,16428,537657,22188,2010,12,2,16,black heart card holder,972,2010-12-07 16:42:00,2.31,18102,United Kingdom,2245.32,NaN
10788,16429,537657,21623,2010,12,2,16,vintage union jack memoboard,408,2010-12-07 16:42:00,6.38,18102,United Kingdom,2603.04,NaN
10789,16430,537658,82484,2010,12,2,16,wood black board ant white finish,48,2010-12-07 16:43:00,4.78,18102,United Kingdom,229.44,NaN
10790,16431,537658,22189,2010,12,2,16,cream heart card holder,36,2010-12-07 16:43:00,2.31,18102,United Kingdom,83.16,NaN
10791,16432,537658,22188,2010,12,2,16,black heart card holder,36,2010-12-07 16:43:00,2.31,18102,United Kingdom,83.16,NaN
10792,16433,537659,22765,2010,12,2,16,newspaper stand,23,2010-12-07 16:43:00,9.89,18102,United Kingdom,227.47,NaN
10793,16434,537659,22507,2010,12,2,16,memo board retrospot design,208,2010-12-07 16:43:00,3.86,18102,United Kingdom,802.88,NaN
10794,16435,537659,22189,2010,12,2,16,cream heart card holder,1008,2010-12-07 16:43:00,2.31,18102,United Kingdom,2328.48,NaN
10795,16436,537659,22188,2010,12,2,16,black heart card holder,1008,2010-12-07 16:43:00,2.31,18102,United Kingdom,2328.48,NaN
10796,16437,537659,21769,2010,12,2,16,vintage post office cabinet,10,2010-12-07 16:43:00,52.77,18102,United Kingdom,527.70,NaN
10797,16438,537659,21623,2010,12,2,16,vintage union jack memoboard,600,2010-12-07 16:43:00,6.38,18102,United Kingdom,3828.00,NaN
10798,16439,537659,85064,2010,12,2,16,cream sweetheart letter rack,160,2010-12-07 16:43:00,3.88,18102,United Kingdom,620.80,NaN
10799,16440,537659,82484,2010,12,2,16,wood black board ant white finish,600,2010-12-07 16:43:00,4.78,18102,United Kingdom,2868.00,NaN
10800,16441,537659,22833,2010,12,2,16,hall cabinet with 3 drawers,72,2010-12-07 16:43:00,32.69,18102,United Kingdom,2353.68,NaN
13607,20528,538063,22830,2010,12,4,13,utilty cabinet with hooks,96,2010-12-09 13:44:00,19.94,18102,United Kingdom,1914.24,678.01
52374,84318,543378,22189,2011,2,1,15,cream heart card holder,504,2011-02-07 15:34:00,2.31,18102,United Kingdom,1164.24,NaN
52375,84319,543378,21623,2011,2,1,15,vintage union jack memoboard,504,2011-02-07 15:34:00,6.38,18102,United Kingdom,3215.52,NaN
52376,84320,543379,82484,2011,2,1,15,wood black board ant white finish,204,2011-02-07 15:37:00,4.77,18102,United Kingdom,973.08,NaN
52377,84321,543379,22507,2011,2,1,15,memo board retrospot design,208,2011-02-07 15:37:00,3.86,18102,United Kingdom,802.88,NaN
52378,84322,543379,22189,2011,2,1,15,cream heart card holder,504,2011-02-07 15:37:00,2.31,18102,United Kingdom,1164.24,NaN
52379,84323,543379,21623,2011,2,1,15,vintage union jack memoboard,504,2011-02-07 15:37:00,6.38,18102,United Kingdom,3215.52,NaN
69365,107882,545466,21621,2011,3,4,9,vintage union jack bunting,200,2011-03-03 09:26:00,6.98,18102,United Kingdom,1396.00,NaN
88927,133989,547812,82484,2011,3,5,14,wood black board ant white finish,300,2011-03-25 14:06:00,4.77,18102,United Kingdom,1431.00,NaN
88928,133990,547812,22507,2011,3,5,14,memo board retrospot design,304,2011-03-25 14:06:00,3.85,18102,United Kingdom,1170.40,NaN
88929,133991,547812,22189,2011,3,5,14,cream heart card holder,432,2011-03-25 14:06:00,2.31,18102,United Kingdom,997.92,NaN
88930,133992,547812,21623,2011,3,5,14,vintage union jack memoboard,300,2011-03-25 14:06:00,6.38,18102,United Kingdom,1914.00,NaN
111785,164840,550711,82484,2011,4,3,11,wood black board ant white finish,108,2011-04-20 11:06:00,4.77,18102,United Kingdom,515.16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322126,439196,574363,23524,2011,11,5,10,wall art horse & pony,120,2011-11-04 10:57:00,2.66,18102,United Kingdom,319.20,NaN
322127,439197,574363,23321,2011,11,5,10,small white heart of wicker,120,2011-11-04 10:57:00,1.11,18102,United Kingdom,133.20,NaN
322155,439225,574383,82484,2011,11,5,11,wood black board ant white finish,1,2011-11-04 11:03:00,4.80,18102,United Kingdom,4.80,NaN
322156,439226,574383,23404,2011,11,5,11,home sweet home blackboard,1,2011-11-04 11:03:00,3.26,18102,United Kingdom,3.26,NaN
322157,439227,574383,23133,2011,11,5,11,large ivory heart wall organiser,12,2011-11-04 11:03:00,5.66,18102,United Kingdom,67.92,NaN
322158,439228,574383,22188,2011,11,5,11,black heart card holder,2,2011-11-04 11:03:00,2.31,18102,United Kingdom,4.62,NaN
374098,506373,579139,85152,2011,11,1,12,hand over the chocolate sign,192,2011-11-28 12:55:00,1.49,18102,United Kingdom,286.08,NaN
397058,540009,581455,22188,2011,12,4,18,black heart card holder,10,2011-12-08 18:25:00,2.31,18102,United Kingdom,23.10,NaN
397059,540010,581455,22189,2011,12,4,18,cream heart card holder,10,2011-12-08 18:25:00,2.31,18102,United Kingdom,23.10,NaN
397060,540011,581455,82484,2011,12,4,18,wood black board ant white finish,12,2011-12-08 18:25:00,4.80,18102,United Kingdom,57.60,NaN
397061,540012,581455,23133,2011,12,4,18,large ivory heart wall organiser,10,2011-12-08 18:25:00,7.05,18102,United Kingdom,70.50,NaN
397062,540013,581455,23553,2011,12,4,18,landmark frame camden town,10,2011-12-08 18:25:00,10.95,18102,United Kingdom,109.50,NaN
397063,540014,581455,23542,2011,12,4,18,wall art 70's alphabet,12,2011-12-08 18:25:00,6.67,18102,United Kingdom,80.04,NaN
397064,540015,581455,23531,2011,12,4,18,wall art big love,12,2011-12-08 18:25:00,4.76,18102,United Kingdom,57.12,NaN
397065,540016,581455,23530,2011,12,4,18,wall art only one person,18,2011-12-08 18:25:00,3.57,18102,United Kingdom,64.26,NaN
397066,540017,581455,23401,2011,12,4,18,rustic mirror with lace heart,18,2011-12-08 18:25:00,4.15,18102,United Kingdom,74.70,NaN
397067,540018,581455,23404,2011,12,4,18,home sweet home blackboard,10,2011-12-08 18:25:00,3.26,18102,United Kingdom,32.60,NaN
397068,540019,581455,23135,2011,12,4,18,small zinc heart wall organiser,18,2011-12-08 18:25:00,3.32,18102,United Kingdom,59.76,NaN
397108,540059,581457,22188,2011,12,4,18,black heart card holder,324,2011-12-08 18:43:00,2.31,18102,United Kingdom,748.44,NaN
397109,540060,581457,22189,2011,12,4,18,cream heart card holder,324,2011-12-08 18:43:00,3.39,18102,United Kingdom,1098.36,NaN
397110,540061,581457,23543,2011,12,4,18,wall art keep calm,698,2011-12-08 18:43:00,4.15,18102,United Kingdom,2896.70,NaN
397111,540062,581457,82484,2011,12,4,18,wood black board ant white finish,204,2011-12-08 18:43:00,4.80,18102,United Kingdom,979.20,NaN
397112,540063,581457,23553,2011,12,4,18,landmark frame camden town,120,2011-12-08 18:43:00,10.95,18102,United Kingdom,1314.00,NaN
397113,540064,581457,23542,2011,12,4,18,wall art 70's alphabet,120,2011-12-08 18:43:00,6.67,18102,United Kingdom,800.40,NaN
397114,540065,581457,23531,2011,12,4,18,wall art big love,120,2011-12-08 18:43:00,4.76,18102,United Kingdom,571.20,NaN
397115,540066,581457,23535,2011,12,4,18,wall art bicycle safety,126,2011-12-08 18:43:00,3.90,18102,United Kingdom,491.40,NaN
397116,540067,581457,23530,2011,12,4,18,wall art only one person,126,2011-12-08 18:43:00,3.57,18102,United Kingdom,449.82,NaN
397117,540068,581457,23526,2011,12,4,18,wall art dog licence,126,2011-12-08 18:43:00,3.90,18102,United Kingdom,491.40,NaN
397118,540069,581457,23401,2011,12,4,18,rustic mirror with lace heart,126,2011-12-08 18:43:00,4.15,18102,United Kingdom,522.90,NaN
397720,541702,581566,23404,2011,12,5,11,home sweet home blackboard,144,2011-12-09 11:50:00,3.26,18102,United Kingdom,469.44,NaN

In [22]:
vip_3_info = orders[orders['CustomerID'] == 17450]
vip_3_info

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_per_customer
9733,14059,537448,21756,2010,12,2,9,bath building block word,6,2010-12-07 09:23:00,6.60,17450,United Kingdom,39.60,NaN
9734,14067,537456,22469,2010,12,2,9,heart of wicker small,402,2010-12-07 09:43:00,1.93,17450,United Kingdom,775.86,NaN
9735,14068,537456,22470,2010,12,2,9,heart of wicker large,378,2010-12-07 09:43:00,3.21,17450,United Kingdom,1213.38,NaN
32186,52131,540689,21733,2011,1,2,8,red hanging heart t-light holder,860,2011-01-11 08:43:00,3.24,17450,United Kingdom,2786.40,NaN
32187,52132,540689,85123A,2011,1,2,8,white hanging heart t-light holder,1010,2011-01-11 08:43:00,3.24,17450,United Kingdom,3272.40,NaN
32188,52133,540689,22469,2011,1,2,8,heart of wicker small,1356,2011-01-11 08:43:00,1.93,17450,United Kingdom,2617.08,NaN
32189,52134,540689,22470,2011,1,2,8,heart of wicker large,1284,2011-01-11 08:43:00,3.21,17450,United Kingdom,4121.64,NaN
32202,52147,540691,22889,2011,1,2,8,number tile vintage font no,24,2011-01-11 08:50:00,2.17,17450,United Kingdom,52.08,NaN
32203,52148,540691,22887,2011,1,2,8,number tile vintage font 8,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32204,52149,540691,22886,2011,1,2,8,number tile vintage font 7,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32205,52150,540691,22885,2011,1,2,8,number tile vintage font 6,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32206,52151,540691,22884,2011,1,2,8,number tile vintage font 5,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32207,52152,540691,22883,2011,1,2,8,number tile vintage font 4,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32208,52153,540691,22882,2011,1,2,8,number tile vintage font 3,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32209,52154,540691,22881,2011,1,2,8,number tile vintage font 2,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32210,52155,540691,22880,2011,1,2,8,number tile vintage font 1,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32211,52156,540691,22879,2011,1,2,8,number tile vintage font 0,16,2011-01-11 08:50:00,2.17,17450,United Kingdom,34.72,NaN
32212,52157,540691,21673,2011,1,2,8,white spot blue ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32213,52158,540691,21672,2011,1,2,8,white spot red ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32214,52159,540691,21671,2011,1,2,8,red spot ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32215,52160,540691,21670,2011,1,2,8,blue spot ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32216,52161,540691,21669,2011,1,2,8,blue stripe ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32217,52162,540691,21668,2011,1,2,8,red stripe ceramic drawer knob,12,2011-01-11 08:50:00,1.49,17450,United Kingdom,17.88,NaN
32218,52163,540691,22775,2011,1,2,8,purple drawerknob acrylic edwardian,18,2011-01-11 08:50:00,1.49,17450,United Kingdom,26.82,NaN
32219,52164,540691,22774,2011,1,2,8,red drawer knob acrylic edwardian,18,2011-01-11 08:50:00,1.49,17450,United Kingdom,26.82,NaN
32220,52165,540691,22773,2011,1,2,8,green drawer knob acrylic edwardian,18,2011-01-11 08:50:00,1.49,17450,United Kingdom,26.82,NaN
32221,52166,540691,22772,2011,1,2,8,pink drawer knob acrylic edwardian,18,2011-01-11 08:50:00,1.49,17450,United Kingdom,26.82,NaN
32222,52167,540691,22771,2011,1,2,8,clear drawer knob acrylic edwardian,18,2011-01-11 08:50:00,1.49,17450,United Kingdom,26.82,NaN
32223,52168,540691,21756,2011,1,2,8,bath building block word,15,2011-01-11 08:50:00,6.60,17450,United Kingdom,99.00,NaN
32224,52169,540691,21755,2011,1,2,8,love building block word,9,2011-01-11 08:50:00,6.60,17450,United Kingdom,59.40,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359387,486759,577747,22365,2011,11,1,14,doormat respectable house,48,2011-11-21 14:21:00,8.00,17450,United Kingdom,384.00,NaN
359388,486760,577747,21523,2011,11,1,14,doormat fancy font home sweet home,48,2011-11-21 14:21:00,8.00,17450,United Kingdom,384.00,NaN
359389,486761,577747,22689,2011,11,1,14,doormat merry christmas red,30,2011-11-21 14:21:00,8.00,17450,United Kingdom,240.00,NaN
359390,486762,577747,82551,2011,11,1,14,laundry 15c metal sign,192,2011-11-21 14:21:00,1.25,17450,United Kingdom,240.00,NaN
359391,486763,577747,82583,2011,11,1,14,hot baths metal sign,240,2011-11-21 14:21:00,2.39,17450,United Kingdom,573.60,NaN
359392,486764,577747,21175,2011,11,1,14,gin + tonic diet metal sign,240,2011-11-21 14:21:00,2.67,17450,United Kingdom,640.80,NaN
359393,486765,577747,48138,2011,11,1,14,doormat union flag,48,2011-11-21 14:21:00,8.00,17450,United Kingdom,384.00,NaN
375726,508563,579249,21181,2011,11,1,16,please one person metal sign,288,2011-11-28 16:32:00,2.39,17450,United Kingdom,688.32,NaN
375727,508564,579249,82600,2011,11,1,16,n0 singing metal sign,192,2011-11-28 16:32:00,2.39,17450,United Kingdom,458.88,NaN
375741,508578,579251,82600,2011,11,1,16,n0 singing metal sign,96,2011-11-28 16:39:00,2.41,17450,United Kingdom,231.36,NaN
375742,508579,579251,22470,2011,11,1,16,heart of wicker large,760,2011-11-28 16:39:00,3.20,17450,United Kingdom,2432.00,NaN
375743,508580,579251,22469,2011,11,1,16,heart of wicker small,600,2011-11-28 16:39:00,1.93,17450,United Kingdom,1158.00,NaN
375744,508581,579252,21174,2011,11,1,16,pottering in the shed metal sign,192,2011-11-28 16:47:00,2.40,17450,United Kingdom,460.80,NaN
375745,508582,579252,21166,2011,11,1,16,cook with wine metal sign,240,2011-11-28 16:47:00,2.39,17450,United Kingdom,573.60,NaN
375746,508583,579253,82600,2011,11,1,16,n0 singing metal sign,96,2011-11-28 16:54:00,2.40,17450,United Kingdom,230.40,NaN
375948,508786,579271,23243,2011,11,2,9,set of tea coffee sugar tins pantry,139,2011-11-29 09:56:00,5.13,17450,United Kingdom,713.07,NaN
375949,508787,579271,22114,2011,11,2,9,hot water bottle tea and sympathy,78,2011-11-29 09:56:00,5.10,17450,United Kingdom,397.80,NaN
375950,508788,579271,22989,2011,11,2,9,set 2 pantry design tea towels,6,2011-11-29 09:56:00,3.28,17450,United Kingdom,19.68,NaN
375951,508789,579271,22993,2011,11,2,9,set of 4 pantry jelly moulds,56,2011-11-29 09:56:00,1.43,17450,United Kingdom,80.08,NaN
375952,508790,579271,22979,2011,11,2,9,pantry washing up brush,78,2011-11-29 09:56:00,1.65,17450,United Kingdom,128.70,NaN
375953,508791,579271,22728,2011,11,2,9,alarm clock bakelike pink,24,2011-11-29 09:56:00,4.08,17450,United Kingdom,97.92,NaN
375954,508792,579271,22730,2011,11,2,9,alarm clock bakelike ivory,20,2011-11-29 09:56:00,4.08,17450,United Kingdom,81.60,NaN
375955,508793,579271,22930,2011,11,2,9,baking mould heart milk chocolate,48,2011-11-29 09:56:00,2.60,17450,United Kingdom,124.80,NaN
375956,508794,579271,22960,2011,11,2,9,jam making set with jars,152,2011-11-29 09:56:00,4.60,17450,United Kingdom,699.20,NaN
375957,508795,579271,22720,2011,11,2,9,set of 3 cake tins pantry design,48,2011-11-29 09:56:00,5.08,17450,United Kingdom,243.84,NaN
381703,517563,580063,82583,2011,12,4,13,hot baths metal sign,96,2011-12-01 13:29:00,2.39,17450,United Kingdom,229.44,NaN
381704,517564,580063,82600,2011,12,4,13,n0 singing metal sign,96,2011-12-01 13:29:00,2.39,17450,United Kingdom,229.44,NaN
381705,517565,580063,21174,2011,12,4,13,pottering in the shed metal sign,144,2011-12-01 13:29:00,2.39,17450,United Kingdom,344.16,NaN
381706,517566,580063,21166,2011,12,4,13,cook with wine metal sign,288,2011-12-01 13:29:00,2.39,17450,United Kingdom,688.32,NaN
381707,517567,580063,82580,2011,12,4,13,bathroom metal sign,96,2011-12-01 13:29:00,0.74,17450,United Kingdom,71.04,NaN

In [23]:
vip_4_info = orders[orders['CustomerID'] == 16446]
vip_4_info

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_per_customer
133752,194354,553573,22980,2011,5,3,9,pantry scrubbing brush,1,2011-05-18 09:52:00,1.65,16446,United Kingdom,1.65,NaN
133753,194355,553573,22982,2011,5,3,9,pantry pastry brush,1,2011-05-18 09:52:00,1.25,16446,United Kingdom,1.25,NaN
397451,540421,581483,23843,2011,12,5,9,"paper craft , little birdie",80995,2011-12-09 09:15:00,2.08,16446,United Kingdom,168469.60,NaN

In [24]:
vip_5_info = orders[orders['CustomerID'] == 14911]
vip_5_info

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,amount_per_customer
1393,1404,536540,22968,2010,12,3,14,rose cottage keepsake box,4,2010-12-01 14:05:00,9.95,14911,EIRE,39.80,NaN
1394,1405,536540,85071A,2010,12,3,14,blue charlie+lola personal doorsign,6,2010-12-01 14:05:00,2.95,14911,EIRE,17.70,NaN
1395,1406,536540,85071C,2010,12,3,14,"charlie+lola""extremely busy"" sign",6,2010-12-01 14:05:00,2.55,14911,EIRE,15.30,NaN
1396,1407,536540,22355,2010,12,3,14,charlotte bag suki design,50,2010-12-01 14:05:00,0.85,14911,EIRE,42.50,NaN
1397,1408,536540,21579,2010,12,3,14,lolita design cotton tote bag,6,2010-12-01 14:05:00,2.25,14911,EIRE,13.50,NaN
1398,1409,536540,21576,2010,12,3,14,lets go shopping cotton tote bag,6,2010-12-01 14:05:00,2.25,14911,EIRE,13.50,NaN
1399,1410,536540,22147,2010,12,3,14,feltcraft butterfly hearts,12,2010-12-01 14:05:00,1.45,14911,EIRE,17.40,NaN
1400,1411,536540,22150,2010,12,3,14,3 stripey mice feltcraft,12,2010-12-01 14:05:00,1.95,14911,EIRE,23.40,NaN
1401,1412,536540,22492,2010,12,3,14,mini paint set vintage,36,2010-12-01 14:05:00,0.65,14911,EIRE,23.40,NaN
1402,1413,536540,22493,2010,12,3,14,paint your own canvas set,24,2010-12-01 14:05:00,1.65,14911,EIRE,39.60,NaN
1403,1414,536540,21833,2010,12,3,14,camouflage led torch,12,2010-12-01 14:05:00,1.69,14911,EIRE,20.28,NaN
1404,1415,536540,85135B,2010,12,3,14,blue dragonfly helicopter,2,2010-12-01 14:05:00,7.95,14911,EIRE,15.90,NaN
1405,1416,536540,85136A,2010,12,3,14,yellow shark helicopter,2,2010-12-01 14:05:00,7.95,14911,EIRE,15.90,NaN
1406,1417,536540,85136C,2010,12,3,14,red shark helicopter,2,2010-12-01 14:05:00,7.95,14911,EIRE,15.90,NaN
1407,1418,536540,21055,2010,12,3,14,tool box soft toy,4,2010-12-01 14:05:00,8.95,14911,EIRE,35.80,NaN
1408,1419,536540,21056,2010,12,3,14,doctor's bag soft toy,4,2010-12-01 14:05:00,8.95,14911,EIRE,35.80,NaN
1409,1420,536540,21889,2010,12,3,14,wooden box of dominoes,24,2010-12-01 14:05:00,1.25,14911,EIRE,30.00,NaN
1410,1421,536540,21891,2010,12,3,14,traditional wooden skipping rope,12,2010-12-01 14:05:00,1.25,14911,EIRE,15.00,NaN
1411,1422,536540,22622,2010,12,3,14,box of vintage alphabet blocks,6,2010-12-01 14:05:00,9.95,14911,EIRE,59.70,NaN
1412,1423,536540,C2,2010,12,3,14,carriage,1,2010-12-01 14:05:00,50.00,14911,EIRE,50.00,NaN
1413,1424,536541,21915,2010,12,3,14,red harmonica in box,12,2010-12-01 14:05:00,1.25,14911,EIRE,15.00,NaN
3543,4785,536803,22113,2010,12,4,16,grey heart hot water bottle,6,2010-12-02 16:33:00,3.75,14911,EIRE,22.50,NaN
4506,6677,536975,84352,2010,12,5,14,silver christmas tree bauble stand,1,2010-12-03 14:04:00,16.95,14911,EIRE,16.95,NaN
4507,6678,536975,22948,2010,12,5,14,metal decoration naughty children,24,2010-12-03 14:04:00,0.85,14911,EIRE,20.40,NaN
4508,6679,536975,22945,2010,12,5,14,christmas metal tags assorted,36,2010-12-03 14:04:00,0.85,14911,EIRE,30.60,NaN
4509,6680,536975,22944,2010,12,5,14,christmas metal postcard with bells,24,2010-12-03 14:04:00,1.25,14911,EIRE,30.00,NaN
4510,6681,536975,22158,2010,12,5,14,3 hearts hanging decoration rustic,8,2010-12-03 14:04:00,2.95,14911,EIRE,23.60,NaN
4511,6682,536975,22572,2010,12,5,14,rocking horse green christmas,12,2010-12-03 14:04:00,0.85,14911,EIRE,10.20,NaN
4512,6683,536975,22571,2010,12,5,14,rocking horse red christmas,12,2010-12-03 14:04:00,0.85,14911,EIRE,10.20,NaN
4513,6684,536975,22246,2010,12,5,14,"garland, magic garden 1.8m",12,2010-12-03 14:04:00,1.95,14911,EIRE,23.40,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396812,539126,581433,84817,2011,12,4,15,danish rose decorative plate,48,2011-12-08 15:54:00,0.39,14911,EIRE,18.72,NaN
396813,539127,581433,84820,2011,12,4,15,danish rose trinket trays,16,2011-12-08 15:54:00,0.79,14911,EIRE,12.64,NaN
396814,539128,581433,84819,2011,12,4,15,danish rose round sewing box,16,2011-12-08 15:54:00,0.79,14911,EIRE,12.64,NaN
396815,539129,581433,84821,2011,12,4,15,danish rose deluxe coaster,24,2011-12-08 15:54:00,0.19,14911,EIRE,4.56,NaN
396816,539130,581433,22171,2011,12,4,15,3 hook photo shelf antique white,2,2011-12-08 15:54:00,8.50,14911,EIRE,17.00,NaN
396817,539131,581433,22914,2011,12,4,15,blue coat rack paris fashion,3,2011-12-08 15:54:00,4.95,14911,EIRE,14.85,NaN
396818,539132,581433,20718,2011,12,4,15,red retrospot shopper bag,10,2011-12-08 15:54:00,1.25,14911,EIRE,12.50,NaN
396819,539133,581433,21108,2011,12,4,15,fairy cake flannel assorted colour,18,2011-12-08 15:54:00,0.79,14911,EIRE,14.22,NaN
396820,539134,581433,21111,2011,12,4,15,"swiss roll towel, chocolate spots",24,2011-12-08 15:54:00,1.25,14911,EIRE,30.00,NaN
396821,539135,581433,82486,2011,12,4,15,3 drawer antique white wood cabinet,4,2011-12-08 15:54:00,8.95,14911,EIRE,35.80,NaN
396822,539136,581433,84509B,2011,12,4,15,set of 4 fairy cake placemats,4,2011-12-08 15:54:00,3.75,14911,EIRE,15.00,NaN
396823,539137,581433,22282,2011,12,4,15,12 egg house painted wood,2,2011-12-08 15:54:00,12.75,14911,EIRE,25.50,NaN
396824,539138,581433,22283,2011,12,4,15,6 egg house painted wood,2,2011-12-08 15:54:00,7.95,14911,EIRE,15.90,NaN
396825,539139,581433,23110,2011,12,4,15,parisienne key cabinet,2,2011-12-08 15:54:00,5.75,14911,EIRE,11.50,NaN
396826,539140,581433,23029,2011,12,4,15,drawer knob crackle glaze green,6,2011-12-08 15:54:00,1.65,14911,EIRE,9.90,NaN
396827,539141,581433,22767,2011,12,4,15,triple photo frame cornice,2,2011-12-08 15:54:00,9.95,14911,EIRE,19.90,NaN
396828,539142,581433,22768,2011,12,4,15,family photo frame cornice,2,2011-12-08 15:54:00,9.95,14911,EIRE,19.90,NaN
396829,539143,581433,22766,2011,12,4,15,photo frame cornice,8,2011-12-08 15:54:00,2.95,14911,EIRE,23.60,NaN
396830,539144,581433,22169,2011,12,4,15,family album white picture frame,2,2011-12-08 15:54:00,8.50,14911,EIRE,17.00,NaN
396831,539145,581433,22796,2011,12,4,15,photo frame 3 classic hanging,2,2011-12-08 15:54:00,9.95,14911,EIRE,19.90,NaN
396832,539146,581433,21210,2011,12,4,15,set of 72 retrospot paper doilies,12,2011-12-08 15:54:00,1.45,14911,EIRE,17.40,NaN
396833,539147,581433,22699,2011,12,4,15,roses regency teacup and saucer,6,2011-12-08 15:54:00,2.95,14911,EIRE,17.70,NaN
396834,539148,581433,22697,2011,12,4,15,green regency teacup and saucer,6,2011-12-08 15:54:00,2.95,14911,EIRE,17.70,NaN
396835,539149,581433,22698,2011,12,4,15,pink regency teacup and saucer,6,2011-12-08 15:54:00,2.95,14911,EIRE,17.70,NaN
396836,539150,581433,23341,2011,12,4,15,pink diner wall clock,2,2011-12-08 15:54:00,8.50,14911,EIRE,17.00,NaN
396837,539151,581433,22192,2011,12,4,15,blue diner wall clock,2,2011-12-08 15:54:00,8.50,14911,EIRE,17.00,NaN
396838,539152,581433,48187,2011,12,4,15,doormat new england,2,2011-12-08 15:54:00,8.25,14911,EIRE,16.50,NaN
396839,539153,581433,48184,2011,12,4,15,doormat english rose,2,2011-12-08 15:54:00,8.25,14911,EIRE,16.50,NaN
396840,539154,581433,20685,2011,12,4,15,doormat red retrospot,2,2011-12-08 15:54:00,8.25,14911,EIRE,16.50,NaN
396841,539155,581433,79302M,2011,12,4,15,"art lights,funk monkey",6,2011-12-08 15:54:00,2.95,14911,EIRE,17.70,NaN




# Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [ ]:
# your code here