In [8]:
#Read CSV & import

import pandas as pd
data = pd.read_csv('GSAF5.csv', encoding='cp1252')
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [17]:
#Check column "Date"

data.loc[:, 'Date']

0                                               18-Sep-16
1                                               18-Sep-16
2                                               18-Sep-16
3                                               17-Sep-16
4                                               16-Sep-16
5                                               15-Sep-16
6                                               11-Sep-16
7                                               07-Sep-16
8                                               06-Sep-16
9                                               05-Sep-16
10                                              05-Sep-16
11                                              04-Sep-16
12                                              01-Sep-16
13                                              29-Aug-16
14                                              29-Aug-16
15                                              27-Aug-16
16                                              25-Aug-16
17                                              07-Aug-16
18                                              06-Aug-16
19                                              04-Aug-16
20                                              29-Jul-16
21                                              28-Jul-16
22                                              28-Jul-16
23                                              27-Jul-16
24                                              26-Jul-16
25                                              24-Jul-16
26                                              23-Jul-16
27                                              23-Jul-16
28                                              20-Jul-16
29                                              17-Jul-16
                              ...
5962                                         World War II
5963                                          Before 1905
5964                              A few years before 1938
5965                                              No date
5966                                          Early 1930s
5967                                          Before 1927
5968                                  Between 1918 & 1939
5969                                              No date
5970                                              No date
5971                                              No date
5972                                           1920 -1923
5973                                          Before 1921
5974                                          Before 1911
5975                                          Before 1921
5976                                          Before 1921
5977                                          Before 1917
5978                          Before          17-Jul-1916
5979    No date (3 days after preceding incident) & pr...
5980                          Before          19-Jul-1913
5981                                          Before 1911
5982                                           Circa 1862
5983                                          Before 1906
5984                                          Before 1906
5985                                          Before 1906
5986                                          Before 1906
5987                                          Before 1903
5988                                          Before 1903
5989                                            1900-1905
5990                                            1883-1889
5991                                            1845-1853
Name: Date, Length: 5992, dtype: object

In [16]:
#Contar y Mostrar columns

data = pd.read_csv('GSAF5.csv', encoding='cp1252')
print(len(data.columns))
print(data.columns)

24
Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [7]:
#Missing Values
null_cols = data.isnull().sum()
null_cols[null_cols > 0]

Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
href formula                 1
href                         3
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64