In [17]:
# Importamos pandas

import pandas as pd
pd.set_option('display.max_columns',50)

In [18]:
# Leemos el archivo 'CSV' con ayuda de un 'encoding'
# '../input' para indicar la nueva ruta del 'CSV'

shark_df = pd.read_csv('../input/GSAF5.csv', encoding = 'iso8859_15')

In [19]:
shark_df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [20]:
# this returns a tuple of the dimensions of the dataframe
shark_df.shape

(5992, 24)

In [21]:
# this returns the datatypes of the columns
shark_df.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [22]:
# although the datatype for 'Injury' appears to be object, further
# investigation shows it's a string
type(shark_df['Injury'][0])

str

In [35]:
# Copia por si acaso
shark_df_aux = shark_df.copy

In [36]:
# PAra ver cuales tienen espacios
shark_df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Species ',
       'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [37]:
shark_df.fillna('.', inplace=True)

In [38]:
# this displays a concise summary of the dataframe,
# including the number of non-null values in each column
shark_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5992 entries, male to male
Data columns (total 23 columns):
Case Number               5992 non-null object
Date                      5992 non-null object
Year                      5992 non-null int64
Type                      5992 non-null object
Country                   5992 non-null object
Area                      5992 non-null object
Location                  5992 non-null object
Activity                  5992 non-null object
Sex                       5992 non-null object
Age                       5992 non-null object
Injury                    5992 non-null object
Fatal (Y/N)               5992 non-null object
Time                      5992 non-null object
Species                   5992 non-null object
Investigator or Source    5992 non-null object
pdf                       5992 non-null object
href formula              5992 non-null object
href                      5992 non-null object
Case Number.1             5992 non-null object
Case Number.2             5992 non-null object
original order            5992 non-null int64
Unnamed: 22               5992 non-null object
Unnamed: 23               5992 non-null object
dtypes: int64(2), object(21)
memory usage: 1.1+ MB

In [39]:
# this returns the number of unique values in each column
shark_df.nunique()

Case Number               5976
Date                      5128
Year                       232
Type                         6
Country                    204
Area                       786
Location                  3930
Activity                  1492
Sex                          6
Age                        152
Injury                    3596
Fatal (Y/N)                  9
Time                       358
Species                   1539
Investigator or Source    4753
pdf                       5981
href formula              5981
href                      5973
Case Number.1             5975
Case Number.2             5976
original order            5988
Unnamed: 22                  2
Unnamed: 23                  3
dtype: int64

In [40]:
shark_df['Fatal (Y/N)'].value_counts()

N          4315
Y          1552
UNKNOWN      94
.            19
 N            8
#VALUE!       1
F             1
N             1
n             1
Name: Fatal (Y/N), dtype: int64

In [41]:
shark_df['Fatal (Y/N)'] = shark_df['Fatal (Y/N)'].replace("Y", True).replace("F", True)
shark_df['Fatal (Y/N)'].value_counts()

N          4315
True       1553
UNKNOWN      94
.            19
 N            8
#VALUE!       1
N             1
n             1
Name: Fatal (Y/N), dtype: int64

In [46]:
shark_df_filtered = shark_df[shark_df['Country']== 'SPAIN']

In [47]:
print(shark_df_filtered)

                                      Case Number                  Date  Year  \
Name
male                                   2016.07.29             29-Jul-16  2016
female                               2016.07.08.R  Reported 08-Jul-2016  2016
Cristina Ojeda-Thies                   2015.12.25             25-Dec-15  2015
male                                 2015.08.18.a             18-Aug-15  2015
male                                 2014.12.03.R  Reported 03-Dec-2014  2014
male                                   2014.09.00                Sep-14  2014
Raquel Martin                        2014.08.27.c             27-Aug-14  2014
child                                  2014.07.20             20-Jul-14  2014
Thierry Frennet                        2013.07.09             07-Jul-13  2013
male                                 2010.07.16.b             16-Jul-10  2010
NaN                                  2009.07.24.a             24-Jul-09  2009
female                                 2006.07.13             13-Jul-06  2006
Jorge Durich Heredia (or Hernandez)    1993.09.03             03-Sep-93  1993
NaN                                    1986.04.00                Apr-86  1986
J. L Pérez-Díaz                        1986.03.18             18-Mar-86  1986
Fuentes Gonzalez Escualo               1980.07.26             26-Jul-80  1980
NaN                                  1970.00.00.g            Late 1970s  1970
female                               1962.00.00.c                  1962  1962
Cecil Bethencourt                      1930.08.16             16-Aug-30  1930
Vicente Bonet                          1929.10.02             02-Oct-29  1929
Sebastian Llopis Puges                 1926.07.03             03-Jul-26  1926
Pascual Gurran                         1925.09.04             04-Sep-25  1925
Boat owned by Ricardo Laneiro          1924.03.24             24-Mar-24  1924
male                                   1916.07.08             08-Jul-16  1916
the governor of Cabrera                1912.00.00                  1912  1912
a soldier                            1911.07.31.R  Reported 31-Jul-1911  1911
male                                 1909.04.27.R  Reported 27-Apr-1909  1909
William Newbury                      1908.08.28.R  Reported 28-Aug-1908  1908
NaN                                  1908.07.18.R  Reported 18-Jul-1908  1908
NaN                                    1879.09.22           22-Sep-1879  1879
male                                   1864.07.25           25-Jul-1864  1864
The widowed Marchioness of Lendinez  1862.08.15.R  Reported 15-Aug-1862  1862
male                                 1862.08.02.R  Reported 02-Aug-1862  1862
Joaquin Rosales Martinez               1862.07.25           25-Jul-1862  1862
male                                   1862.07.14           14-Jul-1862  1862
Tibbetts                               1862.07.13           13-Jul-1862  1862
NaN                                  1836.07.26.R          1836.07.26.R  1836
male                                 1819.07.08.R  Reported 08-Jul-1819  1819
male                                   1764.00.00                  1764  1764
NaN                                       ND-0129           Before 2012     0

                                           Type Country                 Area  \
Name
male                                 Unprovoked   SPAIN    Alicante Province
female                               Unprovoked   SPAIN       Canary Islands
Cristina Ojeda-Thies                 Unprovoked   SPAIN  Grand Canary Island
male                                    Invalid   SPAIN             Alicante
male                                   Provoked   SPAIN              Granada
male                                 Unprovoked   SPAIN            Catalonia
Raquel Martin                        Unprovoked   SPAIN             Alicante
child                                Unprovoked   SPAIN       Canary Islands
Thierry Frennet                         Invalid   SPAIN            Catalonia
male                                   Provoked   SPAIN  Grand Canary Island
NaN                                     Invalid   SPAIN            Catalunya
female                                  Invalid   SPAIN             Alicante
Jorge Durich Heredia (or Hernandez)  Unprovoked   SPAIN         Costa Blanca
NaN                                  Unprovoked   SPAIN            Catalonia
J. L Pérez-Díaz                      Unprovoked   SPAIN                Cádiz
Fuentes Gonzalez Escualo             Unprovoked   SPAIN       Canary Islands
NaN                                  Unprovoked   SPAIN       Canary Islands
female                               Unprovoked   SPAIN            Catalonia
Cecil Bethencourt                    Unprovoked   SPAIN       Canary Islands
Vicente Bonet                        Unprovoked   SPAIN             Valencia
Sebastian Llopis Puges                  Invalid   SPAIN        Sants-Montjic
Pascual Gurran                         Provoked   SPAIN            Valencia
Boat owned by Ricardo Laneiro           Boating   SPAIN               Galica
male                                 Unprovoked   SPAIN         Gran Canaria
the governor of Cabrera              Unprovoked   SPAIN            Balearics
a soldier                            Unprovoked   SPAIN              Málaga
male                                   Provoked   SPAIN            Andalucia
William Newbury                      Unprovoked   SPAIN              Galicia
NaN                                     Invalid   SPAIN       Canary Islands
NaN                                    Provoked   SPAIN             Valencia
male                                 Unprovoked   SPAIN     Eastern Catalona
The widowed Marchioness of Lendinez  Unprovoked   SPAIN                    .
male                                    Invalid   SPAIN               Malaga
Joaquin Rosales Martinez             Unprovoked   SPAIN               Malaga
male                                 Unprovoked   SPAIN                Cádiz
Tibbetts                             Unprovoked   SPAIN                Cádiz
NaN                                     Invalid   SPAIN                    .
male                                    Invalid   SPAIN                    .
male                                 Unprovoked   SPAIN                    .
NaN                                  Unprovoked   SPAIN       Canary Islands

                                                                  Location  \
Name
male                                                      Arenales del Sol
female                                             Las Teresitas, Tenerife
Cristina Ojeda-Thies                  Arinaga Beach, Aguimes, Gran Canaria
male                                              Poniente Beach, Benidorm
male                                                            Off Motril
male                                                                 Salou
Raquel Martin                                                     Benidorm
child                                       Teresita, Santa Cruz, Tenerife
Thierry Frennet                      Sant Marti dEmpuries Beach, LEscala
male                                             Sardina del Norte, Gáldar
NaN                                                          Sant Salvador
female                                                    San Juan Beach
Jorge Durich Heredia (or Hernandez)         Playa de las Arenas, Valencia
NaN                                                          Lloret-de-Mar
J. L Pérez-Díaz                                                    Tarifa
Fuentes Gonzalez Escualo                   San Juan de la Rambla, Tenerife
NaN                                            Icod de los Vinos, Tenerife
female                                                         Aigua Blava
Cecil Bethencourt                                  El Escabonal, Tenerife
Vicente Bonet                                               Nasareth Beach
Sebastian Llopis Puges                       Casa Antunez Beach, Barcelona
Pascual Gurran                                                    Valencia
Boat owned by Ricardo Laneiro                             Sisargas Islands
male                                                            Las Palmas
the governor of Cabrera                                       Isla Cabrera
a soldier                                                            Ceuta
male                                      Puente Mayorga, San Roque, Cádiz
William Newbury                                            Cape Finisterre
NaN                                                    Tazacorte, La Palma
NaN                                                  Castellon de la Plana
male                                                              Badalona
The widowed Marchioness of Lendinez                         A Spanish port
male                                                            Fuengirola
Joaquin Rosales Martinez                                  San Andres Beach
male                                                         Off Algeciras
Tibbetts                                                     Off Algeciras
NaN                                                                      .
male                                                                 Cadiz
male                                                    Guadalquivir River
NaN                                                               Tenerife

                                                                     Activity  \
Name
male                                                                 Swimming
female                                                                 Wading
Cristina Ojeda-Thies                                                 Swimming
male                                                                 Swimming
male                                                  Fishing for blue sharks
male                                             Playing with an air mattress
Raquel Martin                                                        Swimming
child                                                                  Wading
Thierry Frennet                                                      Swimming
male                                                                 Swimming
NaN                                                                  Swimming
female                                                               Swimming
Jorge Durich Heredia (or Hernandez)                                  Swimming
NaN                                                                    Diving
J. L Pérez-Díaz                                                   Windsurfing
Fuentes Gonzalez Escualo                                          Skin diving
NaN                                                              Spearfishing
female                                             Dangling feet in the water
Cecil Bethencourt                                                    Swimming
Vicente Bonet                                                        Fishing
Sebastian Llopis Puges                                                Bathing
Pascual Gurran                                                        Fishing
Boat owned by Ricardo Laneiro                                         Fishing
male                                                                   Diving
the governor of Cabrera                                   Fell into the water
a soldier                                                             Bathing
male                                                                  Fishing
William Newbury                      Fell overboard from P&O steamship Arabia
NaN                                                                         .
NaN                                                                   Fishing
male                                                                  Bathing
The widowed Marchioness of Lendinez                                   Bathing
male                                                                        .
Joaquin Rosales Martinez                                             Swimming
male                                                                        .
Tibbetts                                  Swimming alongside the SS Kearsarge
NaN                                                                         .
male                                                                        .
male                                                                 Swimming
NaN                                                               Skin diving

                                    Sex   Age  \
Name
male                                   M   40
female                                 F   10
Cristina Ojeda-Thies                   F   38
male                                   M   10
male                                   M    .
male                                   M   16
Raquel Martin                          F  30s
child                                  .    .
Thierry Frennet                        M   48
male                                   M    9
NaN                                    F   11
female                                 F    7
Jorge Durich Heredia (or Hernandez)    M   69
NaN                                    M    .
J. L Pérez-Díaz                        M    .
Fuentes Gonzalez Escualo               M    .
NaN                                    M    .
female                                 F    .
Cecil Bethencourt                      M   38
Vicente Bonet                          M    .
Sebastian Llopis Puges                 M    .
Pascual Gurran                         M    .
Boat owned by Ricardo Laneiro          .    .
male                                   M    .
the governor of Cabrera                M    .
a soldier                              M    .
male                                   M    .
William Newbury                        M    .
NaN                                    .    .
NaN                                    .    .
male                                   M    .
The widowed Marchioness of Lendinez    F    .
male                                   M    .
Joaquin Rosales Martinez               M   18
male                                   M   18
Tibbetts                               M    .
NaN                                    .    .
male                                   M    .
male                                   M    .
NaN                                    .    .

                                                                                Injury  \
Name
male                                                         Lacerations to right hand
female                               5 tiny puncture marks to lower leg, treated wi...
Cristina Ojeda-Thies                                       Lacerations to left forearm
male                                  Minor injury when he attempted to touch a fish.
male                                 Glancing bite to wrist from netted shark PROVO...
male                                                         Lacerations to right hand
Raquel Martin                                 Minor lacerations to posterior lower leg
child                                                                     Minor injury
Thierry Frennet                      Scrape to right forearm. Frennet says inflicte...
male                                 Lacerations to left foot when he stepped on th...
NaN                                                            Laceration to left foot
female                                                    Hand & wrist severely bitten
Jorge Durich Heredia (or Hernandez)            Thigh bitten, toes of left foot severed
NaN                                                                          Abrasions
J. L Pérez-Díaz                                                           Foot severed
Fuentes Gonzalez Escualo                                                 Thigh injured
NaN                                                                       Minor injury
female                                                                    Feet severed
Cecil Bethencourt                                                           Leg bitten
Vicente Bonet                                  Arm injured when sharks rammed his boat
Sebastian Llopis Puges                                                       No injury
Pascual Gurran                       Right hand bitten by hooked shark PROVOKED INC...
Boat owned by Ricardo Laneiro                   No injury to occupants, shark bit boat
male                                                                          Survived
the governor of Cabrera                                                          FATAL
a soldier                                                                        FATAL
male                                 Shark knocked him down after he grabbed it by ...
William Newbury                                                                  FATAL
NaN                                  Human remains recovered but shark involvement ...
NaN                                  No injuries to occupants, Hooked shark bit boa...
male                                                                             FATAL
The widowed Marchioness of Lendinez                                           Survived
male                                                  Possible drowning and scavenging
Joaquin Rosales Martinez                                                         FATAL
male                                                                             FATAL
Tibbetts                                                                         FATAL
NaN                                              Shark caught, contained human remains
male                                                             No injury / No attack
male                                                                             FATAL
NaN                                                        Injury required 16 stitches

                                    Fatal (Y/N)     Time  \
Name
male                                          N    11h30
female                                        N        .
Cristina Ojeda-Thies                          N        .
male                                          N    11h00
male                                          N    07h00
male                                          N        .
Raquel Martin                                 N        .
child                                         N        .
Thierry Frennet                               N        .
male                                          N    19h15
NaN                                           N    10h15
female                                        N        .
Jorge Durich Heredia (or Hernandez)           N    08h00
NaN                                           N        .
J. L Pérez-Díaz                               N    10h55
Fuentes Gonzalez Escualo                      N        .
NaN                                           N        .
female                                        N        .
Cecil Bethencourt                             N        .
Vicente Bonet                                 N        .
Sebastian Llopis Puges                        N        .
Pascual Gurran                                N        .
Boat owned by Ricardo Laneiro                 N        .
male                                          N        .
the governor of Cabrera                    True        .
a soldier                                  True        .
male                                          N        .
William Newbury                            True        .
NaN                                        True        .
NaN                                           N        .
male                                       True  Evening

In [ ]:
df_aux_filtered= df_aux[df_aux['Country']== 'SPAIN' ]

In [27]:
# this returns useful descriptive statistics for each column of data
shark_df.describe()

              Year  original order
count  5992.000000     5992.000000
mean   1925.204606     2997.548899
std     286.473712     1729.860210
min       0.000000        2.000000
25%    1942.000000     1499.750000
50%    1975.000000     2997.500000
75%    2003.000000     4495.250000
max    2016.000000     5993.000000

In [28]:
# this returns returns the last few rows
shark_df.tail(2)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,True,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",True,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [29]:
# View the index number and label for each column
for i, v in enumerate(shark_df.columns):
    print(i, v)

0 Case Number
1 Date
2 Year
3 Type
4 Country
5 Area
6 Location
7 Activity
8 Name
9 Sex
10 Age
11 Injury
12 Fatal (Y/N)
13 Time
14 Species
15 Investigator or Source
16 pdf
17 href formula
18 href
19 Case Number.1
20 Case Number.2
21 original order
22 Unnamed: 22
23 Unnamed: 23

In [30]:
# select all the columns from 'id' to the last mean column
shark_df_1 = shark_df.loc[:,'Year':'Injury']
shark_df_1.head()

,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury
0,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh
1,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands
2,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg
3,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg
4,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark

In [31]:
# repeat the step above using index numbers
shark_df = shark_df.iloc[:,:11]
shark_df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN

In [34]:
shark_df = pd.read_csv('../input/GSAF5.csv', encoding = 'iso8859_15', index_col='Name')
shark_df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
Name,,,,,,,,,,,,,,,,,,,,,,,
male,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
Chucky Luciano,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
male,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
Rory Angiolella,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
male,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [16]:
# Let's save the dataframe of means for later.
# shark_df.to_csv('shark_dataset.csv', index=False)