# visualizing real world data project

In [8]:
import numpy as np
import pandas as pd
import matplotlib
%matplotlib inline

In [9]:
tickets = pd.read_csv('../flights_tickets_serp2018-12-16.csv')
tickets.head()

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,cacheId,formattedUrl,...,count,startIndex,inputEncoding,outputEncoding,safe,cx,gl,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $397 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2018-12-16 11:26:30.485612+00:00,106000000,W42baDpas_gJ,https://www.kayak.com/flight-routes/United.../...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.162895,0.16,"106,000,000"
1,flights to hong kong,2,"$480 Flights to Hong Kong, China (HKG) - TripA...",Cheap Flights to Hong Kong: Enter your dates o...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2018-12-16 11:26:30.485612+00:00,106000000,5jsjhmxgxvkJ,https://www.tripadvisor.com/Flights-g294217-Ho...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.162895,0.16,"106,000,000"
2,flights to hong kong,3,Cheap Flights to Hong Kong International from ...,Search cheap flights using Skyscanner's free f...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2018-12-16 11:26:30.485612+00:00,106000000,EI78TI4Q1qYJ,https://www.skyscanner.com/flights-to/hkg/chea...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.162895,0.16,"106,000,000"
3,flights to hong kong,4,Flights to Hong Kong (HKG) | Hong Kong Flight ...,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2018-12-16 11:26:30.485612+00:00,106000000,q6kszaD7mggJ,https://flights.cathaypacific.com/en-us/flight...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.162895,0.16,"106,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $393.97 i...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2018-12-16 11:26:30.485612+00:00,106000000,iEmRbX0P8CAJ,https://www.expedia.com/Cheap-Flights-To-Hong-...,...,10,1,utf8,utf8,off,012859022920491477448:pubdbfjmmec,us,0.162895,0.16,"106,000,000"

In [10]:
tickets.shape

(4000, 26)

In [11]:
tickets.drop(['cacheId','pagemap','gl','formattedUrl','inputEncoding','safe','cx','outputEncoding','htmlSnippet','htmlTitle', 'cseName'], axis=1, inplace=True)

In [12]:
tickets.shape

(4000, 15)

In [13]:
tickets.head()

,searchTerms,rank,title,snippet,displayLink,link,queryTime,totalResults,htmlFormattedUrl,kind,count,startIndex,searchTime,formattedSearchTime,formattedTotalResults
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $397 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,https://www.kayak.com/flight-routes/United-Sta...,2018-12-16 11:26:30.485612+00:00,106000000,https://www.kayak.com/<b>flight</b>-routes/Uni...,customsearch#result,10,1,0.162895,0.16,"106,000,000"
1,flights to hong kong,2,"$480 Flights to Hong Kong, China (HKG) - TripA...",Cheap Flights to Hong Kong: Enter your dates o...,www.tripadvisor.com,https://www.tripadvisor.com/Flights-g294217-Ho...,2018-12-16 11:26:30.485612+00:00,106000000,https://www.tripadvisor.com/<b>Flights</b>-g29...,customsearch#result,10,1,0.162895,0.16,"106,000,000"
2,flights to hong kong,3,Cheap Flights to Hong Kong International from ...,Search cheap flights using Skyscanner's free f...,www.skyscanner.com,https://www.skyscanner.com/flights-to/hkg/chea...,2018-12-16 11:26:30.485612+00:00,106000000,https://www.skyscanner.com/<b>flights-to/hk</b...,customsearch#result,10,1,0.162895,0.16,"106,000,000"
3,flights to hong kong,4,Flights to Hong Kong (HKG) | Hong Kong Flight ...,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,https://flights.cathaypacific.com/en-us/flight...,2018-12-16 11:26:30.485612+00:00,106000000,https://<b>flights</b>.cathaypacific.com/en-us...,customsearch#result,10,1,0.162895,0.16,"106,000,000"
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $393.97 i...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,https://www.expedia.com/Cheap-Flights-To-Hong-...,2018-12-16 11:26:30.485612+00:00,106000000,https://www.expedia.com/Cheap-<b>Flights-To-Ho...,customsearch#result,10,1,0.162895,0.16,"106,000,000"

In [15]:
tickets.drop(['link', 'htmlFormattedUrl', 'kind', 'count', 'formattedSearchTime', 'formattedTotalResults'], axis=1, inplace=True)

In [16]:
tickets.shape

(4000, 9)

In [17]:
tickets.head()

,searchTerms,rank,title,snippet,displayLink,queryTime,totalResults,startIndex,searchTime
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $397 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,2018-12-16 11:26:30.485612+00:00,106000000,1,0.162895
1,flights to hong kong,2,"$480 Flights to Hong Kong, China (HKG) - TripA...",Cheap Flights to Hong Kong: Enter your dates o...,www.tripadvisor.com,2018-12-16 11:26:30.485612+00:00,106000000,1,0.162895
2,flights to hong kong,3,Cheap Flights to Hong Kong International from ...,Search cheap flights using Skyscanner's free f...,www.skyscanner.com,2018-12-16 11:26:30.485612+00:00,106000000,1,0.162895
3,flights to hong kong,4,Flights to Hong Kong (HKG) | Hong Kong Flight ...,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,2018-12-16 11:26:30.485612+00:00,106000000,1,0.162895
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $393.97 i...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,2018-12-16 11:26:30.485612+00:00,106000000,1,0.162895

In [18]:
tickets['startIndex'].unique()

array([1])

In [19]:
tickets.drop(['startIndex'], axis=1, inplace=True)

In [20]:
tickets.head()

,searchTerms,rank,title,snippet,displayLink,queryTime,totalResults,searchTime
0,flights to hong kong,1,Cheap Flights to Hong Kong (HKG) from $397 - K...,"Find flights to Hong Kong on XiamenAir, Hong K...",www.kayak.com,2018-12-16 11:26:30.485612+00:00,106000000,0.162895
1,flights to hong kong,2,"$480 Flights to Hong Kong, China (HKG) - TripA...",Cheap Flights to Hong Kong: Enter your dates o...,www.tripadvisor.com,2018-12-16 11:26:30.485612+00:00,106000000,0.162895
2,flights to hong kong,3,Cheap Flights to Hong Kong International from ...,Search cheap flights using Skyscanner's free f...,www.skyscanner.com,2018-12-16 11:26:30.485612+00:00,106000000,0.162895
3,flights to hong kong,4,Flights to Hong Kong (HKG) | Hong Kong Flight ...,Find & book great deals on Hong Kong (HKG) Fli...,flights.cathaypacific.com,2018-12-16 11:26:30.485612+00:00,106000000,0.162895
4,flights to hong kong,5,"Cheap Flights to Hong Kong SAR, Asia $393.97 i...",Expedia Add-On Advantage: Book a flight & unlo...,www.expedia.com,2018-12-16 11:26:30.485612+00:00,106000000,0.162895

In [33]:
displayLink_unique = tickets['displayLink'].unique()
len(displayLink_unique)

271

In [36]:
searchTerms_unique = tickets['searchTerms'].unique()
len(searchTerms_unique)

200

In [37]:
searchTerms_unique

array(['flights to hong kong', 'flights to bangkok', 'flights to london',
       'flights to singapore', 'flights to macau', 'flights to dubai',
       'flights to paris', 'flights to new york city',
       'flights to shenzhen', 'flights to kuala lumpur',
       'flights to phuket', 'flights to delhi', 'flights to tokyo',
       'flights to rome', 'flights to taipei', 'flights to guangzhou',
       'flights to mumbai', 'flights to mecca', 'flights to istanbul',
       'flights to prague', 'flights to miami', 'flights to seoul',
       'flights to barcelona', 'flights to pattaya',
       'flights to shanghai', 'flights to milan', 'flights to cancÃºn',
       'flights to agra', 'flights to las vegas', 'flights to amsterdam',
       'flights to antalya', 'flights to denpasar', 'flights to osaka',
       'flights to los angeles', 'flights to vienna', 'flights to berlin',
       'flights to madrid', 'flights to johor bahru',
       'flights to johannesburg', 'flights to riyadh',
       'flights to ho chi minh city', 'flights to venice',
       'flights to orlando', 'flights to chennai', 'flights to jaipur',
       'flights to athens', 'flights to dublin', 'flights to florence',
       'flights to moscow', 'flights to toronto', 'flights to hanoi',
       'flights to beijing', 'flights to ha long', 'flights to sydney',
       'flights to budapest', 'flights to punta cana',
       'flights to san francisco', 'flights to jakarta',
       'flights to dammam', 'flights to munich', 'flights to lisbon',
       'flights to zhuhai', 'flights to heraklion',
       'flights to penang island', 'flights to cairo',
       'flights to copenhagen', 'flights to kyoto',
       'flights to phnom penh', 'flights to doha',
       'flights to chiang mai', 'flights to edirne',
       'flights to jerusalem', 'flights to saint petersburg',
       'flights to warsaw', 'flights to melbourne',
       'flights to marrakesh', 'flights to vancouver',
       'flights to auckland', 'flights to tel aviv',
       'flights to honolulu', 'flights to artvin', 'flights to kolkata',
       'flights to krakÃ³w', 'flights to guilin', 'flights to brussels',
       'flights to frankfurt am main', 'flights to stockholm',
       'flights to jeju', 'flights to mexico city',
       'flights to siem reap', 'flights to lima',
       'flights to rio de janeiro', 'flights to rhodes',
       'flights to buenos aires', 'flights to colombo',
       'flights to abu dhabi', 'flights to taichung',
       'flights to washington d.c.', 'flights to chiba',
       'flights to nice', 'tickets to hong kong', 'tickets to bangkok',
       'tickets to london', 'tickets to singapore', 'tickets to macau',
       'tickets to dubai', 'tickets to paris', 'tickets to new york city',
       'tickets to shenzhen', 'tickets to kuala lumpur',
       'tickets to phuket', 'tickets to delhi', 'tickets to tokyo',
       'tickets to rome', 'tickets to taipei', 'tickets to guangzhou',
       'tickets to mumbai', 'tickets to mecca', 'tickets to istanbul',
       'tickets to prague', 'tickets to miami', 'tickets to seoul',
       'tickets to barcelona', 'tickets to pattaya',
       'tickets to shanghai', 'tickets to milan', 'tickets to cancÃºn',
       'tickets to agra', 'tickets to las vegas', 'tickets to amsterdam',
       'tickets to antalya', 'tickets to denpasar', 'tickets to osaka',
       'tickets to los angeles', 'tickets to vienna', 'tickets to berlin',
       'tickets to madrid', 'tickets to johor bahru',
       'tickets to johannesburg', 'tickets to riyadh',
       'tickets to ho chi minh city', 'tickets to venice',
       'tickets to orlando', 'tickets to chennai', 'tickets to jaipur',
       'tickets to athens', 'tickets to dublin', 'tickets to florence',
       'tickets to moscow', 'tickets to toronto', 'tickets to hanoi',
       'tickets to beijing', 'tickets to ha long', 'tickets to sydney',
       'tickets to budapest', 'tickets to punta cana',
       'tickets to san francisco', 'tickets to jakarta',
       'tickets to dammam', 'tickets to munich', 'tickets to lisbon',
       'tickets to zhuhai', 'tickets to heraklion',
       'tickets to penang island', 'tickets to cairo',
       'tickets to copenhagen', 'tickets to kyoto',
       'tickets to phnom penh', 'tickets to doha',
       'tickets to chiang mai', 'tickets to edirne',
       'tickets to jerusalem', 'tickets to saint petersburg',
       'tickets to warsaw', 'tickets to melbourne',
       'tickets to marrakesh', 'tickets to vancouver',
       'tickets to auckland', 'tickets to tel aviv',
       'tickets to honolulu', 'tickets to artvin', 'tickets to kolkata',
       'tickets to krakÃ³w', 'tickets to guilin', 'tickets to brussels',
       'tickets to frankfurt am main', 'tickets to stockholm',
       'tickets to jeju', 'tickets to mexico city',
       'tickets to siem reap', 'tickets to lima',
       'tickets to rio de janeiro', 'tickets to rhodes',
       'tickets to buenos aires', 'tickets to colombo',
       'tickets to abu dhabi', 'tickets to taichung',
       'tickets to washington d.c.', 'tickets to chiba',
       'tickets to nice'], dtype=object)

In [39]:
split = tickets['searchTerms'].split('tickets to ')

AttributeError: 'Series' object has no attribute 'split'