In [63]:
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint

In [64]:
def get_csv(csv_file, enconding_value):
    df = pd.read_csv(csv_file, encoding = enconding_value, na_values=["-", False])
    return df

collisions = get_csv("traffic-collision-data-from-2010-to-present.csv", "latin-1")
collisions.head(10)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1216,10,West Valley,1009,997,TRAFFIC COLLISION,NaN,...,STREET,ROSCOE,HASKELL,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1445,7,Wilshire,762,997,TRAFFIC COLLISION,NaN,...,STREET,ALFRED ST,PICO BL,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1245,20,Olympic,2029,997,TRAFFIC COLLISION,NaN,...,STREET,WILSHIRE,VERMONT,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1120,6,Hollywood,645,997,TRAFFIC COLLISION,NaN,...,STREET,HOLLYWOOD BL,ORANGE DR,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1015,16,Foothill,1653,997,TRAFFIC COLLISION,NaN,...,STREET,ARLETA AV,BRANFORD ST,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,630,4,Hollenbeck,455,997,TRAFFIC COLLISION,NaN,...,STREET,STATE ST,E 10FWY,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1,13,Newton,1325,997,TRAFFIC COLLISION,NaN,...,STREET,CENTRAL AV,28TH ST,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1300,7,Wilshire,785,997,TRAFFIC COLLISION,NaN,...,STREET,WEST BL,18TH ST,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1155,16,Foothill,1656,997,TRAFFIC COLLISION,NaN,...,STREET,ELDORA AV,APPERSON ST,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,30,19,Mission,1925,997,TRAFFIC COLLISION,NaN,...,STREET,BRADLEY AV,ASTORIA ST,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [65]:
def rename_column(df, old_column, new_column):
    return df.rename(columns = {old_column: new_column}, inplace = True)

collision_type = rename_column(collisions, "Crime Code Description", "Collision type")

collisions.head(10)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Collision type,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1216,10,West Valley,1009,997,TRAFFIC COLLISION,NaN,...,STREET,ROSCOE,HASKELL,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1445,7,Wilshire,762,997,TRAFFIC COLLISION,NaN,...,STREET,ALFRED ST,PICO BL,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1245,20,Olympic,2029,997,TRAFFIC COLLISION,NaN,...,STREET,WILSHIRE,VERMONT,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1120,6,Hollywood,645,997,TRAFFIC COLLISION,NaN,...,STREET,HOLLYWOOD BL,ORANGE DR,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1015,16,Foothill,1653,997,TRAFFIC COLLISION,NaN,...,STREET,ARLETA AV,BRANFORD ST,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,630,4,Hollenbeck,455,997,TRAFFIC COLLISION,NaN,...,STREET,STATE ST,E 10FWY,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1,13,Newton,1325,997,TRAFFIC COLLISION,NaN,...,STREET,CENTRAL AV,28TH ST,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1300,7,Wilshire,785,997,TRAFFIC COLLISION,NaN,...,STREET,WEST BL,18TH ST,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1155,16,Foothill,1656,997,TRAFFIC COLLISION,NaN,...,STREET,ELDORA AV,APPERSON ST,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,30,19,Mission,1925,997,TRAFFIC COLLISION,NaN,...,STREET,BRADLEY AV,ASTORIA ST,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [66]:
def capitalize_column_values(df, column):
    df[column] = df[column].str.capitalize()

capitalize_column_values(collisions, "Address")
capitalize_column_values(collisions, "Cross Street")
capitalize_column_values(collisions, "Premise Description")
capitalize_column_values(collisions, "Collision type")


collisions.head(9)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Collision type,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1216,10,West Valley,1009,997,Traffic collision,NaN,...,Street,Roscoe,Haskell,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1445,7,Wilshire,762,997,Traffic collision,NaN,...,Street,Alfred st,Pico bl,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1245,20,Olympic,2029,997,Traffic collision,NaN,...,Street,Wilshire,Vermont,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1120,6,Hollywood,645,997,Traffic collision,NaN,...,Street,Hollywood bl,Orange dr,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1015,16,Foothill,1653,997,Traffic collision,NaN,...,Street,Arleta av,Branford st,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,630,4,Hollenbeck,455,997,Traffic collision,NaN,...,Street,State st,E 10fwy,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1,13,Newton,1325,997,Traffic collision,NaN,...,Street,Central av,28th st,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1300,7,Wilshire,785,997,Traffic collision,NaN,...,Street,West bl,18th st,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1155,16,Foothill,1656,997,Traffic collision,NaN,...,Street,Eldora av,Apperson st,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,30,19,Mission,1925,997,Traffic collision,NaN,...,Street,Bradley av,Astoria st,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [67]:
collisions.drop(["LA Specific Plans", "Premise Code", "Precinct Boundaries", "Council Districts", "Victim Descent","MO Codes", "Census Tracts", "Neighborhood Councils (Certified)"], axis = 1)

collisions.head(10)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Collision type,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1216,10,West Valley,1009,997,Traffic collision,NaN,...,Street,Roscoe,Haskell,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1445,7,Wilshire,762,997,Traffic collision,NaN,...,Street,Alfred st,Pico bl,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1245,20,Olympic,2029,997,Traffic collision,NaN,...,Street,Wilshire,Vermont,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1120,6,Hollywood,645,997,Traffic collision,NaN,...,Street,Hollywood bl,Orange dr,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1015,16,Foothill,1653,997,Traffic collision,NaN,...,Street,Arleta av,Branford st,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,630,4,Hollenbeck,455,997,Traffic collision,NaN,...,Street,State st,E 10fwy,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1,13,Newton,1325,997,Traffic collision,NaN,...,Street,Central av,28th st,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1300,7,Wilshire,785,997,Traffic collision,NaN,...,Street,West bl,18th st,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,1155,16,Foothill,1656,997,Traffic collision,NaN,...,Street,Eldora av,Apperson st,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08T00:00:00.000,2019-06-08T00:00:00.000,30,19,Mission,1925,997,Traffic collision,NaN,...,Street,Bradley av,Astoria st,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [68]:
collisions["Date Occurred"] = collisions["Date Occurred"].apply(lambda value: value[0:10])
collisions["Date Reported"] = collisions["Date Reported"].apply(lambda value: value[0:10])
            
collisions.head(10)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Collision type,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08,2019-06-08,1216,10,West Valley,1009,997,Traffic collision,NaN,...,Street,Roscoe,Haskell,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08,2019-06-08,1445,7,Wilshire,762,997,Traffic collision,NaN,...,Street,Alfred st,Pico bl,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08,2019-06-08,1245,20,Olympic,2029,997,Traffic collision,NaN,...,Street,Wilshire,Vermont,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08,2019-06-08,1120,6,Hollywood,645,997,Traffic collision,NaN,...,Street,Hollywood bl,Orange dr,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08,2019-06-08,1015,16,Foothill,1653,997,Traffic collision,NaN,...,Street,Arleta av,Branford st,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08,2019-06-08,630,4,Hollenbeck,455,997,Traffic collision,NaN,...,Street,State st,E 10fwy,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08,2019-06-08,1,13,Newton,1325,997,Traffic collision,NaN,...,Street,Central av,28th st,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08,2019-06-08,1300,7,Wilshire,785,997,Traffic collision,NaN,...,Street,West bl,18th st,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08,2019-06-08,1155,16,Foothill,1656,997,Traffic collision,NaN,...,Street,Eldora av,Apperson st,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08,2019-06-08,30,19,Mission,1925,997,Traffic collision,NaN,...,Street,Bradley av,Astoria st,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [69]:
collisions.sort_values(by='Date Reported', ascending=True)

collisions.head(10)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Collision type,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,191010770,2019-06-08,2019-06-08,1216,10,West Valley,1009,997,Traffic collision,NaN,...,Street,Roscoe,Haskell,"{'human_address': '{""address"": """", ""city"": """",...",18914.0,121.0,426.0,NaN,2.0,88.0
1,190711820,2019-06-08,2019-06-08,1445,7,Wilshire,762,997,Traffic collision,NaN,...,Street,Alfred st,Pico bl,"{'human_address': '{""address"": """", ""city"": """",...",23666.0,641.0,1102.0,NaN,12.0,23.0
2,192011837,2019-06-08,2019-06-08,1245,20,Olympic,2029,997,Traffic collision,NaN,...,Street,Wilshire,Vermont,"{'human_address': '{""address"": """", ""city"": """",...",22726.0,578.0,684.0,NaN,12.0,89.0
3,190613201,2019-06-08,2019-06-08,1120,6,Hollywood,645,997,Traffic collision,NaN,...,Street,Hollywood bl,Orange dr,"{'human_address': '{""address"": """", ""city"": """",...",23446.0,414.0,1303.0,NaN,8.0,82.0
4,191610033,2019-06-08,2019-06-08,1015,16,Foothill,1653,997,Traffic collision,NaN,...,Street,Arleta av,Branford st,"{'human_address': '{""address"": """", ""city"": """",...",18907.0,34.0,451.0,NaN,1.0,11.0
5,190410808,2019-06-08,2019-06-08,630,4,Hollenbeck,455,997,Traffic collision,NaN,...,Street,State st,E 10fwy,"{'human_address': '{""address"": """", ""city"": """",...",23450.0,512.0,509.0,NaN,9.0,38.0
6,191312833,2019-06-08,2019-06-08,1,13,Newton,1325,997,Traffic collision,NaN,...,Street,Central av,28th st,"{'human_address': '{""address"": """", ""city"": """",...",22727.0,708.0,971.0,7.0,13.0,6.0
7,190711819,2019-06-08,2019-06-08,1300,7,Wilshire,785,997,Traffic collision,NaN,...,Street,West bl,18th st,"{'human_address': '{""address"": """", ""city"": """",...",23077.0,655.0,1111.0,NaN,12.0,69.0
8,191610034,2019-06-08,2019-06-08,1155,16,Foothill,1656,997,Traffic collision,NaN,...,Street,Eldora av,Apperson st,"{'human_address': '{""address"": """", ""city"": """",...",3221.0,15.0,1511.0,NaN,1.0,7.0
9,191911558,2019-06-08,2019-06-08,30,19,Mission,1925,997,Traffic collision,NaN,...,Street,Bradley av,Astoria st,"{'human_address': '{""address"": """", ""city"": """",...",18912.0,60.0,363.0,NaN,1.0,47.0

In [72]:
collisions[['Date Reported','Date Occurred']] = pd.to_datetime(collisions[['Date Reported','Date Occurred']], yearfirst=arfirst = True)

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing

In [61]:
collisions.dtypes

DR Number                                     int64
Date Reported                        datetime64[ns]
Date Occurred                                object
Time Occurred                                 int64
Area ID                                       int64
Area Name                                    object
Reporting District                            int64
Crime Code                                    int64
Collision type                               object
MO Codes                                     object
Victim Age                                  float64
Victim Sex                                   object
Victim Descent                               object
Premise Code                                float64
Premise Description                          object
Address                                      object
Cross Street                                 object
Location                                     object
Zip Codes                                   float64
Census Tracts                               float64
Precinct Boundaries                         float64
LA Specific Plans                           float64
Council Districts                           float64
Neighborhood Councils (Certified)           float64
(Date Reported, Date Occurred)       datetime64[ns]
dtype: object

In [56]:
collisions.loc[Date Occurred,['2018-03-01':'2018-03-31']]
collisions[collisions.some_date.between('2018-03-01', '2018-03-31')]

SyntaxError: invalid syntax (<ipython-input-56-07462f86beca>, line 1)